(()=>{"use strict";
const $=id=>document.getElementById(id),cv=$("board"),ctx=cv.getContext("2d",{alpha:false}),CW=cv.width,CH=cv.height;
const scoreEl=$("score"),aliveEl=$("alive"),killsEl=$("kills"),statusEl=$("status"),clockEl=$("clock"),difficultyEl=$("difficulty"),targetAIEl=$("targetAI"),pressureEl=$("pressureLabel"),streakEl=$("streakLabel"),joy=$("joy"),stick=$("stick"),boostBtn=$("boost"),speedEl=$("speed"),skinNameEl=$("skinName"),killBanner=$("killBanner"),killFlash=$("killFlash"),leaderEl=$("leader"),musicBtn=$("musicBtn"),sfxBtn=$("sfxBtn"),soundGate=$("soundGate"),startGameBtn=$("startGame"),stopBtn=$("stop"),stage=document.querySelector(".stage");
const fxEls={magnet:$("fxMagnet"),speed:$("fxSpeed"),shield:$("fxShield"),growth:$("fxGrowth")},skinBtns=[...document.querySelectorAll(".skin")];
const WORLD=180,SCALE=18.5,BASE_SPEED=6.2,BOOST=1.5,PLAYER_TURN=5.4,AI_BASE_SPEED=5.9,PLAYER_R=.43,BODY_R=.49,TRAIL_GAP=.18,SPAWN_PROTECT=2.1,PLAYER_RESPAWN=2.3,BASE_FOOD_TARGET=500,POWERUP_TARGET=8,MAGNET_RADIUS=10.5;
const FOOD_COLORS=["#55e3ff","#ffd85a","#ff6c93","#b27cff","#67e08a","#ff9d50","#6f9cff","#f16b6f"],POWERUP_TYPES=["magnet","speed","shield","growth"];
const SKINS={qinglong:{name:"青龙",body:"#29b77f",head:"#53e6a7",accent:"#efd267"},neon:{name:"霓虹",body:"#4f69ff",head:"#6bf4ff",accent:"#e85dff"},lava:{name:"熔岩",body:"#96392a",head:"#ff6b2c",accent:"#ffd166"},ice:{name:"冰晶",body:"#75d8ff",head:"#c9f4ff",accent:"#fff"},star:{name:"星空",body:"#5149ad",head:"#8278f0",accent:"#f2edff"},candy:{name:"糖果",body:"#ff79b8",head:"#ffb7da",accent:"#7ef1ea"},mech:{name:"机甲",body:"#78899a",head:"#bdcbd6",accent:"#f2c14f"},bee:{name:"蜂纹",body:"#efbd35",head:"#ffd75d",accent:"#23272e"}};
let player,ais=[],foods=[],powerups=[],cam={x:90,y:90},targetAngle=0,last=performance.now(),raf=0,joyPointer=null,boosting=false,ended=false,playerRespawn=0,currentSkin="qinglong",effects={magnet:0,speed:0,growth:0,shield:0},elapsed=0,spawnTicker=0,uiTicker=0,score=0,kills=0,killStreak=0,comboCount=0,lastKillAt=-999,comboTimer=0,currentTargetAI=14,currentDifficulty=1,currentPressure=0,gameStopped=true,userStarted=false,audioCtx=null,musicTimer=null,musicStep=0,sfxOn=true,musicOn=true;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),d2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};
function wrap(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}function turn(a,b,m){return a+clamp(wrap(b-a),-m,m)}function inside(p,m=.5){return p.x>=m&&p.y>=m&&p.x<=WORLD-m&&p.y<=WORLD-m}function rp(m=5){return{x:m+Math.random()*(WORLD-2*m),y:m+Math.random()*(WORLD-2*m)}}function fmt(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(Math.floor(s%60)).padStart(2,"0")}
async function unlockAudio(){if(!audioCtx){try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}}if(audioCtx&&audioCtx.state==="suspended"){try{await audioCtx.resume()}catch(e){}}if(musicOn&&audioCtx&&!musicTimer)startMusic();return !!audioCtx&&audioCtx.state==="running"}
function tone(f=440,d=.08,g=.08,type="sine",delay=0){if(!audioCtx||!sfxOn||audioCtx.state!=="running")return;const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(audioCtx.destination);o.start(t);o.stop(t+d+.02)}
function sfx(k){if(k==="food"){tone(680,.05,.06);tone(980,.04,.03,"sine",.025)}else if(k==="power"){tone(460,.10,.10,"triangle");tone(760,.13,.08,"triangle",.05);tone(1080,.12,.05,"sine",.11)}else if(k==="kill"){tone(120,.12,.16,"square");tone(300,.16,.12,"sawtooth",.03);tone(680,.20,.09,"triangle",.09)}else if(k==="death"){tone(170,.25,.17,"sawtooth");tone(80,.40,.12,"triangle",.07)}else if(k==="shield"){tone(720,.13,.11);tone(1120,.16,.08,"sine",.05)}else if(k==="boost"){tone(330,.08,.07,"square");tone(520,.07,.04,"triangle",.04)}else if(k==="milestone"){tone(110,.14,.18,"square");tone(360,.18,.15,"sawtooth",.04);tone(740,.22,.12,"triangle",.10);tone(1080,.28,.08,"sine",.18)}}
function startMusic(){if(!audioCtx||musicTimer||!musicOn||audioCtx.state!=="running")return;const lead=[220,277,330,440,330,494,370,277],bass=[110,110,139,139,165,165,139,123];musicTimer=setInterval(()=>{if(!musicOn||!audioCtx||audioCtx.state!=="running")return;const t=audioCtx.currentTime,i=musicStep++%lead.length,o=audioCtx.createOscillator(),g=audioCtx.createGain(),b=audioCtx.createOscillator(),bg=audioCtx.createGain();o.type="triangle";o.frequency.value=lead[i];g.gain.setValueAtTime(.055,t);g.gain.exponentialRampToValueAtTime(.0001,t+.18);b.type="square";b.frequency.value=bass[i];bg.gain.setValueAtTime(.035,t);bg.gain.exponentialRampToValueAtTime(.0001,t+.13);o.connect(g);g.connect(audioCtx.destination);b.connect(bg);bg.connect(audioCtx.destination);o.start(t);o.stop(t+.19);b.start(t);b.stop(t+.14)},214)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function seedTrail(s,n){s.trail=[];for(let i=0;i<n;i++)s.trail.push({x:s.x-Math.cos(s.angle)*TRAIL_GAP*i,y:s.y-Math.sin(s.angle)*TRAIL_GAP*i})}function addTrail(s){const p={x:s.x,y:s.y};if(!s.trail.length||dist(p,s.trail[0])>=TRAIL_GAP)s.trail.unshift(p);const cap=Math.min(700,Math.max(50,Math.round(s.lengthPts)));if(s.trail.length>cap)s.trail.length=cap}function hitTrail(p,t,skip=0,r=.52){const rr=r*r;for(let i=skip;i<t.length;i+=3)if(d2(p,t[i])<rr)return true;return false}
function pSpeed(){return 1+(boosting?.5:0)+(effects.speed>0?.3:0)}function aiSpeed(a){return 1+(a.effects.speed>0?.3:0)+(a.sprintTimer>0?.36:0)}
function safeSpawn(forPlayer=false){for(let i=0;i<150;i++){const p=rp(12);if(ais.every(a=>!a.alive||dist(p,a)>(forPlayer?14:7))&&(!player||forPlayer||dist(p,player)>16))return p}return rp(15)}
function makePlayer(){const s={id:"player",x:90,y:90,angle:0,trail:[],lengthPts:110,spawnProtect:SPAWN_PROTECT,skin:currentSkin};seedTrail(s,72);return s}
function makeAI(){const p=safeSpawn(),r=Math.random(),len=r<.35?75+Math.random()*55:r<.72?135+Math.random()*95:r<.94?235+Math.random()*130:380+Math.random()*120,aggr=.42+Math.random()*.5,elite=Math.random()<clamp(.06+elapsed/3600,.06,.25);const a={id:"ai_"+Math.random().toString(36).slice(2),x:p.x,y:p.y,angle:Math.random()*Math.PI*2,trail:[],lengthPts:len,alive:true,respawn:0,spawnProtect:SPAWN_PROTECT,skin:Object.keys(SKINS)[Math.floor(Math.random()*8)],effects:{magnet:0,speed:0,growth:0,shield:0},target:null,targetCooldown:0,aggr:elite?Math.max(.8,aggr):aggr,elite,sprintTimer:0,sprintCooldown:1.5+Math.random()*4,loopSamples:[],sampleTimer:0,escapeTimer:0,escapeAngle:0,loopLock:0,lastX:p.x,lastY:p.y,progressTimer:0,attackMode:"seek",wobble:Math.random()*20};seedTrail(a,Math.min(430,Math.max(52,Math.round(len*.72))));return a}
function bodyWidth(s){return Math.min(26,10.5+Math.max(0,s.lengthPts-70)*.035)}
function difficulty(){const m=elapsed/60,base=Math.min(2.5,1+m*.075);currentDifficulty=clamp(base+killStreak*.012,1,2.55);let n=m<3?14+m:m<8?17+(m-3)*1.15:23+Math.min(7,(m-8)*.7);currentTargetAI=Math.round(clamp(n,14,30));const live=ais.filter(a=>a.alive);currentPressure=clamp(live.reduce((s,a)=>s+a.lengthPts,0)/(Math.max(1,live.length)*250)*.55+live.length/30*.45,0,1)}
function ensureAI(){difficulty();const live=ais.filter(a=>a.alive).length;if(live>=currentTargetAI)return;const dead=ais.find(a=>!a.alive&&a.respawn<=0);if(dead)Object.assign(dead,makeAI());else if(ais.length<30)ais.push(makeAI())}
function newFood(drop=false,x=null,y=null){const p=x==null?rp(4):{x,y};return{x:p.x,y:p.y,drop,bornAt:elapsed,color:drop?"#ffd45a":FOOD_COLORS[Math.floor(Math.random()*FOOD_COLORS.length)],value:drop?1.8:1}}function newPower(type=null,x=null,y=null){const p=x==null?rp(10):{x,y};return{x:p.x,y:p.y,type:type||POWERUP_TYPES[Math.floor(Math.random()*4)],phase:Math.random()*6.28}}
function reserveDropSlots(need){let extra=Math.max(0,foods.length+need-1700);for(let i=0;i<foods.length&&extra>0;){if(!foods[i].drop){foods.splice(i,1);extra--}else i++}}
function dropBody(s){const pts=[];for(let i=0;i<s.trail.length;i+=2){const p=s.trail[i];if(inside(p,1))pts.push(p)}reserveDropSlots(pts.length+4);for(const p of pts)foods.push(newFood(true,p.x,p.y));if(!pts.length&&inside(s,1))foods.push(newFood(true,s.x,s.y))}
function eatFood(a,isPlayer){let ate=0;for(let i=foods.length-1;i>=0;i--)if(d2(a,foods[i])<.78*.78){const f=foods[i];foods.splice(i,1);ate++;if(isPlayer){score+=f.drop?14:10;player.lengthPts=Math.min(650,player.lengthPts+(effects.growth>0?10:5)*(f.drop?1.2:1));if(ate===1)sfx("food")}else a.lengthPts=Math.min(680,a.lengthPts+4*f.value*(a.effects.growth>0?2:1))}if(isPlayer&&ate)scoreEl.textContent=Math.round(score)}
function collectPower(a,isPlayer){for(let i=powerups.length-1;i>=0;i--)if(d2(a,powerups[i])<1.25*1.25){const t=powerups[i].type;powerups.splice(i,1);const e=isPlayer?effects:a.effects;if(t==="shield")e.shield=Math.min(2,e.shield+1);else e[t]=Math.max(e[t],t==="speed"?6:8);if(isPlayer){sfx("power");statusEl.textContent={magnet:"磁铁开启",speed:"疾速开启",shield:"获得护盾",growth:"双倍成长"}[t]}}}
function updateEffects(e,dt){for(const k of["magnet","speed","growth"])e[k]=Math.max(0,e[k]-dt)}function magnet(a,e,dt){if(e.magnet<=0)return;for(const o of [...foods,...powerups]){const dd=d2(a,o);if(dd>MAGNET_RADIUS*MAGNET_RADIUS||dd<.001)continue;const d=Math.sqrt(dd),q=(2+(MAGNET_RADIUS-d)*1.7)*dt;o.x+=(a.x-o.x)/d*q;o.y+=(a.y-o.y)/d*q}}
function consumeShield(a,isPlayer,msg){const e=isPlayer?effects:a.effects;if(e.shield<=0)return false;e.shield--;a.spawnProtect=Math.max(a.spawnProtect,.9);if(isPlayer){sfx("shield");statusEl.textContent="护盾抵挡："+msg}return true}
function replenish(){let normal=foods.filter(f=>!f.drop).length,target=Math.round(BASE_FOOD_TARGET+(currentDifficulty-1)*80);while(normal<target){foods.push(newFood());normal++}for(let i=foods.length-1;i>=0;i--)if(foods[i].drop&&elapsed-foods[i].bornAt>34)foods.splice(i,1);while(foods.length>1700){const i=foods.findIndex(f=>!f.drop);if(i<0)break;foods.splice(i,1)}while(powerups.length<POWERUP_TARGET)powerups.push(newPower())}
function speak(t){if(!sfxOn||!("speechSynthesis" in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=1.08;u.pitch=.78;u.volume=1;speechSynthesis.speak(u)}catch(e){}}
function banner(text,cls=""){killBanner.textContent=text;killBanner.className="kill-banner show "+cls;killFlash.classList.remove("show");stage.classList.remove("shake");void killFlash.offsetWidth;killFlash.classList.add("show");stage.classList.add("shake");setTimeout(()=>{killBanner.classList.remove("show");stage.classList.remove("shake")},1050)}
function recordKill(){kills++;killStreak++;comboCount=elapsed-lastKillAt<=8?comboCount+1:1;lastKillAt=elapsed;comboTimer=8;const m={2:["DOUBLE KILL · 双杀","Double Kill","c2"],3:["TRIPLE KILL · 三杀","Triple Kill","c3"],4:["QUADRA KILL · 四杀","Quadra Kill","c4"],5:["PENTA KILL · 五杀","Penta Kill","c5"]};if(m[comboCount]){banner(m[comboCount][0],m[comboCount][2]);sfx(comboCount>=4?"milestone":"kill");speak(m[comboCount][1])}else sfx("kill");if(killStreak===10){banner("LEGENDARY · 十连斩","legend");sfx("milestone");speak("Legendary")}if(killStreak===15){banner("UNSTOPPABLE · 十五连斩","legend");sfx("milestone");speak("Unstoppable")}score+=25}
function killAI(a,msg,credit=false){if(!a.alive)return;dropBody(a);a.alive=false;a.respawn=3+Math.random()*2.4;a.trail=[];if(credit)recordKill();statusEl.textContent=msg}
function diePlayer(msg){if(ended)return;dropBody(player);ended=true;playerRespawn=PLAYER_RESPAWN;boosting=false;boostBtn.classList.remove("active");effects={magnet:0,speed:0,growth:0,shield:0};killStreak=0;comboCount=0;sfx("death");statusEl.textContent=msg+" · 2.3秒后复活"}
function respawnPlayer(){const p=safeSpawn(true);Object.assign(player,{x:p.x,y:p.y,angle:Math.random()*6.28,lengthPts:110,spawnProtect:SPAWN_PROTECT});targetAngle=player.angle;seedTrail(player,72);ended=false;playerRespawn=0;cam={x:player.x,y:player.y};statusEl.textContent="已复活 · 全身保护"}
function danger(a,ang,look=2.7){const p={x:a.x+Math.cos(ang)*look,y:a.y+Math.sin(ang)*look};if(!inside(p,1.8))return true;if(!ended&&player.spawnProtect<=0&&hitTrail(p,player.trail,10,.72))return true;for(const o of ais)if(o!==a&&o.alive&&dist(a,o)<22&&hitTrail(p,o.trail,10,.7))return true;return false}
function forceEscape(a,sign=1){a.escapeTimer=2.1+Math.random()*.8;a.loopLock=5+Math.random()*2.5;a.escapeAngle=wrap(a.angle-(sign||1)*(1.05+Math.random()*.55));for(let k=0;k<5&&danger(a,a.escapeAngle,3.2);k++)a.escapeAngle=wrap(a.escapeAngle+(Math.random()<.5?-1:1)*.55);a.target=null;a.loopSamples=[]}
function monitorLoop(a,dt){a.loopLock=Math.max(0,a.loopLock-dt);a.progressTimer+=dt;a.sampleTimer-=dt;if(a.progressTimer>=2.4){const moved=Math.hypot(a.x-a.lastX,a.y-a.lastY);if(moved<3.6&&a.loopLock<=0)forceEscape(a,Math.random()<.5?-1:1);a.lastX=a.x;a.lastY=a.y;a.progressTimer=0}if(a.sampleTimer>0)return;a.sampleTimer=.20;a.loopSamples.push({x:a.x,y:a.y,angle:a.angle});if(a.loopSamples.length>18)a.loopSamples.shift();if(a.loopSamples.length<12||a.loopLock>0)return;let signed=0,abs=0;for(let i=1;i<a.loopSamples.length;i++){const da=wrap(a.loopSamples[i].angle-a.loopSamples[i-1].angle);signed+=da;abs+=Math.abs(da)}const f=a.loopSamples[0],net=Math.hypot(a.x-f.x,a.y-f.y);if((Math.abs(signed)>Math.PI*1.72&&net<8.5)||(abs>Math.PI*2.4&&net<7.5))forceEscape(a,Math.sign(signed)||1)}
function selectVictim(a){if(ended||player.spawnProtect>0)return null;const dp=dist(a,player);if(dp<52&&(a.aggr>.56||a.elite||Math.random()<.22*currentDifficulty))return player;let best=null,bd=1e9;for(const o of ais)if(o!==a&&o.alive&&o.spawnProtect<=0&&o.lengthPts<a.lengthPts*1.12){const d=dist(a,o);if(d<bd&&d<34){best=o;bd=d}}return best}
function nearestFood(a){let b=null,bd=1e9;for(const f of foods){const dd=d2(a,f)*(f.drop?.45:1);if(dd<bd){bd=dd;b=f}}return b}
function chooseAI(a,dt,time){if(a.escapeTimer>0){a.escapeTimer=Math.max(0,a.escapeTimer-dt);return a.escapeAngle}a.targetCooldown-=dt;if(a.targetCooldown<=0||!a.target||(!a.target.alive&&a.target.id)){a.targetCooldown=clamp(.65/currentDifficulty*(.75+Math.random()*.5),.12,.72);a.target=selectVictim(a)||nearestFood(a)}let aim=a.angle;const t=a.target;if(t){if(t.id){const d=dist(a,t),tv=t===player?BASE_SPEED*pSpeed():AI_BASE_SPEED*aiSpeed(t),lead=clamp(d/Math.max(5,tv)*.42,.38,1.55),px=t.x+Math.cos(t.angle)*tv*lead,py=t.y+Math.sin(t.angle)*tv*lead;let side=Math.sign(Math.sin(t.angle)*(a.x-t.x)-Math.cos(t.angle)*(a.y-t.y))||1,off=clamp(d*.18,2.2,6.2);if(d<9){a.attackMode="cut";aim=t.angle+side*Math.PI*.52}else if(d<28){a.attackMode="intercept";aim=Math.atan2(py+Math.cos(t.angle)*off*side-a.y,px-Math.sin(t.angle)*off*side-a.x)}else{a.attackMode="hunt";aim=Math.atan2(py-a.y,px-a.x)}if(a.sprintCooldown<=0&&d<26&&a.attackMode!=="hunt"){a.sprintTimer=.9+Math.random()*.65;a.sprintCooldown=3.2+Math.random()*3.6}}else{a.attackMode="feed";aim=Math.atan2(t.y-a.y,t.x-a.x)}}aim+=Math.sin(time*.0012+a.wobble)*.025;if(!danger(a,aim,2.6))return aim;for(const z of[a.angle,a.angle-.22,a.angle+.22,a.angle-.48,a.angle+.48,a.angle-.82,a.angle+.82])if(!danger(a,z,2.8))return z;if(a.loopLock<=0)forceEscape(a,Math.random()<.5?-1:1);return a.escapeTimer>0?a.escapeAngle:a.angle}
function updatePlayer(dt){player.spawnProtect=Math.max(0,player.spawnProtect-dt);updateEffects(effects,dt);player.angle=turn(player.angle,targetAngle,PLAYER_TURN*dt);const v=BASE_SPEED*pSpeed();player.x+=Math.cos(player.angle)*v*dt;player.y+=Math.sin(player.angle)*v*dt;magnet(player,effects,dt);addTrail(player);eatFood(player,true);collectPower(player,true);if(!inside(player,PLAYER_R)){if(consumeShield(player,true,"边界碰撞")){player.x=clamp(player.x,1.5,WORLD-1.5);player.y=clamp(player.y,1.5,WORLD-1.5);targetAngle=player.angle=wrap(player.angle+Math.PI*.85);return}diePlayer("撞到边界");return}if(player.spawnProtect>0)return;for(const a of ais){if(!a.alive||a.spawnProtect>0)continue;if(dist(player,a)<.68){const ps=effects.shield>0,as=a.effects.shield>0;if(ps&&!as){consumeShield(player,true,"正面碰撞");killAI(a,"护盾反杀 AI",true);return}if(as&&!ps){consumeShield(a,false,"正面碰撞");diePlayer("被 AI 正面截杀");return}killAI(a,"正面相撞",false);diePlayer("正面撞上 AI");return}if(hitTrail(player,a.trail,8,BODY_R+.08)){if(consumeShield(player,true,"撞到 AI 身体"))return;diePlayer(a.attackMode==="cut"?"被 AI 横切封路击杀":"撞到 AI 身体");return}}}
function updateAI(a,dt,time){if(!a.alive){a.respawn-=dt;return}a.spawnProtect=Math.max(0,a.spawnProtect-dt);updateEffects(a.effects,dt);a.sprintCooldown=Math.max(0,a.sprintCooldown-dt);a.sprintTimer=Math.max(0,a.sprintTimer-dt);monitorLoop(a,dt);const desired=chooseAI(a,dt,time),pen=clamp((a.lengthPts-100)/850,0,.22),rate=(2.45+currentDifficulty*.42+(a.elite?.45:0))*(1-pen);a.angle=turn(a.angle,desired,rate*dt);const v=AI_BASE_SPEED*aiSpeed(a)*(a.elite?1.05:1);a.x+=Math.cos(a.angle)*v*dt;a.y+=Math.sin(a.angle)*v*dt;magnet(a,a.effects,dt);addTrail(a);eatFood(a,false);collectPower(a,false);if(!inside(a,.75)){a.x=clamp(a.x,1.1,WORLD-1.1);a.y=clamp(a.y,1.1,WORLD-1.1);const cx=WORLD/2-a.x,cy=WORLD/2-a.y;a.angle=Math.atan2(cy,cx);a.escapeAngle=a.angle;a.escapeTimer=1.1;a.loopLock=Math.max(a.loopLock,2);return}if(a.spawnProtect>0)return;if(!ended&&player.spawnProtect<=0&&dist(a,player)<.68){const as=a.effects.shield>0,ps=effects.shield>0;if(as&&!ps){consumeShield(a,false,"正面");diePlayer("被 AI 护盾截杀");return}if(ps&&!as){consumeShield(player,true,"正面");killAI(a,"护盾反杀 AI",true);return}killAI(a,"正面相撞",false);diePlayer("被 AI 正面撞杀");return}if(!ended&&hitTrail(a,player.trail,8,.56)){killAI(a,"你截杀了一条 AI",true);return}for(const o of ais)if(o!==a&&o.alive&&o.spawnProtect<=0&&dist(a,o)<22&&hitTrail(a,o.trail,8,.56)){killAI(a,"AI 被另一条蛇截杀");return}}
function scr(p){return{x:(p.x-cam.x)*SCALE+CW/2,y:(p.y-cam.y)*SCALE+CH/2}}function visible(p,pad=45){const q=scr(p);return q.x>-pad&&q.y>-pad&&q.x<CW+pad&&q.y<CH+pad}function snakeVisible(s,pad=190){if(visible(s,pad))return true;for(let i=0;i<s.trail.length;i+=4)if(visible(s.trail[i],pad))return true;return false}
function polyline(s){if(!s.trail.length)return;let p=scr(s.trail[0]);ctx.beginPath();ctx.moveTo(p.x,p.y);for(let i=1;i<s.trail.length;i++){const q=scr(s.trail[i]);ctx.lineTo(q.x,q.y)}}
function drawWorld(){ctx.fillStyle="#771e27";ctx.fillRect(0,0,CW,CH);const tl=scr({x:0,y:0}),br=scr({x:WORLD,y:WORLD}),g=ctx.createLinearGradient(0,0,CW,CH);g.addColorStop(0,"#101b25");g.addColorStop(1,"#0a1118");ctx.fillStyle=g;ctx.fillRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.strokeStyle="#ff5865";ctx.lineWidth=5;ctx.strokeRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y)}
function drawSnake(s,isPlayer=false){if(!s.trail.length||!snakeVisible(s))return;const sk=SKINS[s.skin]||SKINS.qinglong,w=bodyWidth(s),h=scr(s);ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="rgba(0,0,0,.72)";ctx.lineWidth=w+7;polyline(s);ctx.stroke();ctx.strokeStyle=sk.body;ctx.lineWidth=w+3;polyline(s);ctx.stroke();ctx.strokeStyle=sk.head;ctx.lineWidth=w;polyline(s);ctx.stroke();ctx.fillStyle=sk.head;ctx.beginPath();ctx.arc(h.x,h.y,w*.64,0,6.28);ctx.fill();if(!isPlayer&&s.elite){ctx.strokeStyle="#ffd96a";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,w*.86,0,6.28);ctx.stroke()}if((isPlayer?effects.shield:s.effects.shield)>0){ctx.strokeStyle="rgba(102,214,255,.85)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,w*.95+5,0,6.28);ctx.stroke()}if(s.spawnProtect>0){ctx.strokeStyle="rgba(220,240,255,.72)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,Math.max(38,w*2.9),0,6.28);ctx.stroke()}ctx.restore()}
function draw(){drawWorld();const tl=scr({x:0,y:0}),br=scr({x:WORLD,y:WORLD});ctx.save();ctx.beginPath();ctx.rect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.clip();for(const f of foods)if(visible(f,20)){const p=scr(f);ctx.save();ctx.fillStyle=f.color;if(f.drop){ctx.shadowBlur=16;ctx.shadowColor="#ffd45a"}ctx.beginPath();ctx.arc(p.x,p.y,f.drop?6.5:4,0,6.28);ctx.fill();ctx.restore()}for(const p of powerups)if(visible(p,30)){const q=scr(p);ctx.fillStyle="#13283a";ctx.strokeStyle="#9ee3ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,14,0,6.28);ctx.fill();ctx.stroke();ctx.font="15px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(p.type==="magnet"?"🧲":p.type==="speed"?"⚡":p.type==="shield"?"🛡️":"⭐",q.x,q.y)}for(const a of ais)if(a.alive)drawSnake(a,false);if(!ended)drawSnake(player,true);ctx.restore()}
function ui(){aliveEl.textContent=ais.filter(a=>a.alive).length;targetAIEl.textContent=currentTargetAI;difficultyEl.textContent=currentDifficulty.toFixed(2);clockEl.textContent=fmt(elapsed);pressureEl.textContent=`竞技场压力 ${Math.round(currentPressure*100)}%`;streakEl.textContent=`连斩 ${killStreak}`;scoreEl.textContent=Math.round(score);killsEl.textContent=kills;speedEl.textContent=`速度 ${Math.round(pSpeed()*100)}%`;for(const k of POWERUP_TYPES){fxEls[k].classList.toggle("on",effects[k]>0);fxEls[k].textContent={magnet:"🧲 磁铁",speed:"⚡ 疾速",shield:"🛡️ 护盾",growth:"⭐ 双倍成长"}[k]+(effects[k]>0?" "+(k==="shield"?"×"+effects[k]:effects[k].toFixed(1)+"s"):"")}const rows=[];if(!ended)rows.push({n:"你",l:player.lengthPts});for(const a of ais)if(a.alive)rows.push({n:(a.elite?"★ ":"")+SKINS[a.skin].name+" AI",l:a.lengthPts});rows.sort((a,b)=>b.l-a.l);leaderEl.innerHTML="<b>排行榜</b>　"+rows.slice(0,5).map((r,i)=>`${i+1}. ${r.n} ${Math.round(r.l)}`).join("　")}
function step(dt,time){if(gameStopped)return;elapsed+=dt;spawnTicker-=dt;uiTicker-=dt;comboTimer=Math.max(0,comboTimer-dt);if(!comboTimer)comboCount=0;if(ended){playerRespawn-=dt;if(playerRespawn<=0)respawnPlayer()}else updatePlayer(dt);for(const a of ais)updateAI(a,dt,time);if(spawnTicker<=0){spawnTicker=.7;ensureAI()}replenish();const f=1-Math.exp(-7*dt);cam.x+=(player.x-cam.x)*f;cam.y+=(player.y-cam.y)*f;if(uiTicker<=0){uiTicker=.2;ui()}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;step(dt,now);draw();raf=requestAnimationFrame(loop)}
function setBoost(v){boosting=!!v&&!ended&&!gameStopped;boostBtn.classList.toggle("active",boosting);if(boosting)sfx("boost")}
function moveJoy(e){const b=joy.getBoundingClientRect(),dx=e.clientX-(b.left+b.width/2),dy=e.clientY-(b.top+b.height/2),l=Math.hypot(dx,dy)||1,max=b.width*.29,k=Math.min(1,max/l);stick.style.transform=`translate(${dx*k}px,${dy*k}px)`;if(l>4)targetAngle=Math.atan2(dy,dx)}function clearJoy(){joyPointer=null;stick.style.transform="translate(0,0)"}
joy.addEventListener("pointerdown",async e=>{await unlockAudio();joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)});joy.addEventListener("pointermove",e=>{if(e.pointerId===joyPointer)moveJoy(e)});joy.addEventListener("pointerup",e=>{if(e.pointerId===joyPointer)clearJoy()});joy.addEventListener("pointercancel",clearJoy);boostBtn.addEventListener("pointerdown",async e=>{await unlockAudio();boostBtn.setPointerCapture(e.pointerId);setBoost(true)});boostBtn.addEventListener("pointerup",()=>setBoost(false));boostBtn.addEventListener("pointercancel",()=>setBoost(false));
function setSkin(n){if(!SKINS[n])return;currentSkin=n;if(player)player.skin=n;skinNameEl.textContent=SKINS[n].name;skinBtns.forEach(b=>b.classList.toggle("active",b.dataset.skin===n))}
function reset(){cancelAnimationFrame(raf);elapsed=0;score=0;kills=0;killStreak=0;comboCount=0;lastKillAt=-999;effects={magnet:0,speed:0,growth:0,shield:0};foods=[];powerups=[];ais=[];player=makePlayer();cam={x:90,y:90};targetAngle=player.angle;ended=false;for(let i=0;i<14;i++)ais.push(makeAI());for(let i=0;i<BASE_FOOD_TARGET;i++)foods.push(newFood());for(let i=0;i<POWERUP_TARGET;i++)powerups.push(newPower());gameStopped=!userStarted;last=performance.now();difficulty();ui();raf=requestAnimationFrame(loop)}
async function start(){await unlockAudio();userStarted=true;gameStopped=false;soundGate.classList.add("hidden");statusEl.textContent="竞技中";stopBtn.textContent="暂停";last=performance.now();tone(660,.09,.055,"triangle");tone(920,.12,.045,"triangle",.07)}
startGameBtn.addEventListener("click",start);$("restart").onclick=async()=>{await unlockAudio();userStarted=true;soundGate.classList.add("hidden");reset()};stopBtn.onclick=async()=>{await unlockAudio();if(!userStarted){await start();return}gameStopped=!gameStopped;stopBtn.textContent=gameStopped?"继续":"暂停";statusEl.textContent=gameStopped?"已暂停":"竞技中";if(!gameStopped)last=performance.now()};musicBtn.onclick=async()=>{await unlockAudio();musicOn=!musicOn;musicBtn.classList.toggle("off",!musicOn);musicOn?startMusic():stopMusic()};sfxBtn.onclick=async()=>{await unlockAudio();sfxOn=!sfxOn;sfxBtn.classList.toggle("off",!sfxOn);sfxBtn.textContent=sfxOn?"🔊":"🔇"};skinBtns.forEach(b=>b.onclick=()=>setSkin(b.dataset.skin));document.addEventListener("visibilitychange",()=>{if(document.hidden)setBoost(false)});
window.__snakeTest={snapshot:()=>({version:"V4.3",elapsed,difficulty:currentDifficulty,targetAI:currentTargetAI,aliveAI:ais.filter(a=>a.alive).length,foodCount:foods.length,kills,killStreak,playerCanTightCircle:true,aiLoopEscape:true,aiAttackModes:["hunt","intercept","cut"],dropReserve:true}),forceAILoop:(i=0)=>{const a=ais[i];a.loopLock=0;a.loopSamples=[];for(let j=0;j<18;j++)a.loopSamples.push({x:a.x+Math.cos(j*.45),y:a.y+Math.sin(j*.45),angle:wrap(a.angle+j*.52)});a.sampleTimer=0;monitorLoop(a,.21);return{escapeTimer:a.escapeTimer,loopLock:a.loopLock}},forceAIHunt:(i=0)=>{const a=ais[i];a.aggr=1;a.target=player;a.targetCooldown=1;return{mode:a.attackMode,angle:chooseAI(a,.016,performance.now())}},forceDeath:(i=0)=>{const before=foods.length;killAI(ais[i],"测试死亡",false);return{before,after:foods.length,drops:foods.filter(f=>f.drop).length}}};
setSkin("qinglong");reset();
})();