(()=>{"use strict";
const $=id=>document.getElementById(id),cv=$("board"),ctx=cv.getContext("2d",{alpha:false}),CW=cv.width,CH=cv.height;
const scoreEl=$("score"),aliveEl=$("alive"),killsEl=$("kills"),statusEl=$("status"),clockEl=$("clock"),difficultyEl=$("difficulty"),targetAIEl=$("targetAI"),pressureEl=$("pressureLabel"),streakEl=$("streakLabel"),joy=$("joy"),stick=$("stick"),boostBtn=$("boost"),fireBtn=$("fire"),fireCount=$("fireCount"),speedEl=$("speed"),skinNameEl=$("skinName"),killBanner=$("killBanner"),killFlash=$("killFlash"),leaderEl=$("leader"),musicBtn=$("musicBtn"),sfxBtn=$("sfxBtn"),soundGate=$("soundGate"),startGameBtn=$("startGame"),stopBtn=$("stop"),stage=document.querySelector(".stage");
const fxEls={magnet:$("fxMagnet"),speed:$("fxSpeed"),shield:$("fxShield"),growth:$("fxGrowth"),cannon:$("fxCannon")},skinBtns=[...document.querySelectorAll(".skin")];
const WORLD=180,SCALE=18.5,BASE_SPEED=6.2,BOOST=1.5,PLAYER_TURN=5.4,AI_BASE_SPEED=6.0,PLAYER_R=.43,BODY_R=.49,TRAIL_GAP=.18,SPAWN_PROTECT=2.1,PLAYER_RESPAWN=2.3,BASE_FOOD_TARGET=500,POWERUP_TARGET=9,MAGNET_RADIUS=10.5,BULLET_SPEED=17.5;
const FOOD_COLORS=["#55e3ff","#ffd85a","#ff6c93","#b27cff","#67e08a","#ff9d50","#6f9cff","#f16b6f"],POWERUP_TYPES=["magnet","speed","shield","growth","cannon"];
const SKINS={qinglong:{name:"青龙",body:"#29b77f",head:"#53e6a7",accent:"#efd267"},neon:{name:"霓虹",body:"#4f69ff",head:"#6bf4ff",accent:"#e85dff"},lava:{name:"熔岩",body:"#96392a",head:"#ff6b2c",accent:"#ffd166"},ice:{name:"冰晶",body:"#75d8ff",head:"#c9f4ff",accent:"#ffffff"},star:{name:"星空",body:"#5149ad",head:"#8278f0",accent:"#f2edff"},candy:{name:"糖果",body:"#ff79b8",head:"#ffb7da",accent:"#7ef1ea"},mech:{name:"机甲",body:"#78899a",head:"#bdcbd6",accent:"#f2c14f"},bee:{name:"蜂纹",body:"#efbd35",head:"#ffd75d",accent:"#23272e"}};
let player,ais=[],foods=[],powerups=[],bullets=[],foodGrid=new Map(),foodDirty=false,cam={x:90,y:90},targetAngle=0,last=performance.now(),raf=0,joyPointer=null,boosting=false,ended=false,playerRespawn=0,currentSkin="qinglong",effects={magnet:0,speed:0,growth:0,shield:0},elapsed=0,spawnTicker=0,uiTicker=0,replenishTicker=0,score=0,kills=0,killStreak=0,comboCount=0,lastKillAt=-999,comboTimer=0,currentTargetAI=14,currentDifficulty=1,currentPressure=0,gameStopped=true,userStarted=false,audioCtx=null,musicTimer=null,musicStep=0,sfxOn=true,musicOn=true;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),d2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};
function wrap(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}function turn(a,b,m){return a+clamp(wrap(b-a),-m,m)}function inside(p,m=.5){return p.x>=m&&p.y>=m&&p.x<=WORLD-m&&p.y<=WORLD-m}function rp(m=5){return{x:m+Math.random()*(WORLD-2*m),y:m+Math.random()*(WORLD-2*m)}}function fmt(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(Math.floor(s%60)).padStart(2,"0")}
async function unlockAudio(){if(!audioCtx){try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}}if(audioCtx&&audioCtx.state==="suspended"){try{await audioCtx.resume()}catch(e){}}if(musicOn&&audioCtx&&!musicTimer)startMusic();return !!audioCtx&&audioCtx.state==="running"}
function tone(f=440,d=.08,g=.08,type="sine",delay=0){if(!audioCtx||!sfxOn||audioCtx.state!=="running")return;const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(audioCtx.destination);o.start(t);o.stop(t+d+.02)}
function sfx(k){if(k==="food"){tone(720,.04,.07);tone(1020,.035,.035,"sine",.02)}else if(k==="power"){tone(470,.09,.13,"triangle");tone(800,.12,.10,"triangle",.04);tone(1180,.14,.07,"sine",.09)}else if(k==="kill"){tone(110,.13,.20,"square");tone(330,.16,.15,"sawtooth",.03);tone(720,.20,.11,"triangle",.08)}else if(k==="death"){tone(160,.28,.20,"sawtooth");tone(70,.42,.15,"triangle",.07)}else if(k==="shield"){tone(760,.13,.13);tone(1160,.16,.10,"sine",.05)}else if(k==="boost"){tone(350,.07,.08,"square");tone(540,.07,.05,"triangle",.03)}else if(k==="fire"){tone(105,.06,.24,"square");tone(320,.08,.16,"sawtooth",.015);tone(820,.07,.08,"triangle",.045)}else if(k==="hit"){tone(190,.08,.18,"square");tone(520,.07,.10,"sawtooth",.025)}else if(k==="milestone"){tone(105,.15,.22,"square");tone(380,.18,.18,"sawtooth",.04);tone(780,.22,.15,"triangle",.10);tone(1160,.30,.10,"sine",.18)}}
function startMusic(){if(!audioCtx||musicTimer||!musicOn||audioCtx.state!=="running")return;const lead=[220,277,330,440,330,494,370,277],bass=[110,110,139,139,165,165,139,123];musicTimer=setInterval(()=>{if(!musicOn||!audioCtx||audioCtx.state!=="running")return;const t=audioCtx.currentTime,i=musicStep++%lead.length,o=audioCtx.createOscillator(),g=audioCtx.createGain(),b=audioCtx.createOscillator(),bg=audioCtx.createGain();o.type="triangle";o.frequency.value=lead[i];g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.0001,t+.18);b.type="square";b.frequency.value=bass[i];bg.gain.setValueAtTime(.05,t);bg.gain.exponentialRampToValueAtTime(.0001,t+.13);o.connect(g);g.connect(audioCtx.destination);b.connect(bg);bg.connect(audioCtx.destination);o.start(t);o.stop(t+.19);b.start(t);b.stop(t+.14)},214)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function seedTrail(s,n){s.trail=[];for(let i=0;i<n;i++)s.trail.push({x:s.x-Math.cos(s.angle)*TRAIL_GAP*i,y:s.y-Math.sin(s.angle)*TRAIL_GAP*i})}
function addTrail(s){const p={x:s.x,y:s.y};if(!s.trail.length||dist(p,s.trail[0])>=TRAIL_GAP)s.trail.unshift(p);const cap=Math.min(620,Math.max(50,Math.round(s.lengthPts)));if(s.trail.length>cap)s.trail.length=cap}
function hitTrail(p,t,skip=0,r=.52,step=3){const rr=r*r;for(let i=skip;i<t.length;i+=step)if(d2(p,t[i])<rr)return true;return false}
function findTrailHit(p,t,skip=7,r=.52){const rr=r*r;for(let i=skip;i<t.length;i+=2)if(d2(p,t[i])<rr)return i;return-1}
function pSpeed(){return 1+(boosting?.5:0)+(effects.speed>0?.3:0)}function aiSpeed(a){return 1+(a.effects.speed>0?.3:0)+(a.sprintTimer>0?.42:0)}
function safeSpawn(forPlayer=false){for(let i=0;i<100;i++){const p=rp(12);if(ais.every(a=>!a.alive||dist(p,a)>(forPlayer?14:7))&&(!player||forPlayer||dist(p,player)>16))return p}return rp(15)}
function makePlayer(){const s={id:"player",x:90,y:90,angle:0,trail:[],lengthPts:110,spawnProtect:SPAWN_PROTECT,skin:currentSkin,cannonShots:0,bodyShotHits:0};seedTrail(s,72);return s}
function makeAI(){const p=safeSpawn(),r=Math.random(),len=r<.35?75+Math.random()*55:r<.72?135+Math.random()*95:r<.94?235+Math.random()*130:380+Math.random()*120,aggr=.52+Math.random()*.46,elite=Math.random()<clamp(.08+elapsed/3000,.08,.28),tactics=["hunter","interceptor","ambusher"];const a={id:"ai_"+Math.random().toString(36).slice(2),x:p.x,y:p.y,angle:Math.random()*Math.PI*2,trail:[],lengthPts:len,alive:true,respawn:0,spawnProtect:SPAWN_PROTECT,skin:Object.keys(SKINS)[Math.floor(Math.random()*8)],effects:{magnet:0,speed:0,growth:0,shield:0},cannonShots:0,bodyShotHits:0,fireCooldown:1+Math.random()*2,target:null,targetCooldown:0,aggr:elite?Math.max(.86,aggr):aggr,elite,tactic:tactics[Math.floor(Math.random()*tactics.length)],sprintTimer:0,sprintCooldown:1+Math.random()*3,loopSamples:[],sampleTimer:0,escapeTimer:0,escapeAngle:0,loopLock:0,lastX:p.x,lastY:p.y,progressTimer:0,attackMode:"seek",wobble:Math.random()*20,thinkTimer:Math.random()*.15,desiredAngle:Math.random()*6.28,collisionTimer:Math.random()*.05,foodSeed:Math.floor(Math.random()*7)};seedTrail(a,Math.min(390,Math.max(52,Math.round(len*.68))));return a}
function bodyWidth(s){return Math.min(26,10.5+Math.max(0,s.lengthPts-70)*.035)}
function difficulty(){const m=elapsed/60,base=Math.min(2.55,1+m*.08);currentDifficulty=clamp(base+killStreak*.012,1,2.6);let n=m<3?14+m*.8:m<8?16+(m-3):21+Math.min(6,(m-8)*.65);currentTargetAI=Math.round(clamp(n,14,27));const live=ais.filter(a=>a.alive);currentPressure=clamp(live.reduce((s,a)=>s+a.lengthPts,0)/(Math.max(1,live.length)*245)*.56+live.length/27*.44,0,1)}
function ensureAI(){difficulty();const live=ais.filter(a=>a.alive).length;if(live>=currentTargetAI)return;const dead=ais.find(a=>!a.alive&&a.respawn<=0);if(dead)Object.assign(dead,makeAI());else if(ais.length<27)ais.push(makeAI())}
function newFood(drop=false,x=null,y=null){const p=x==null?rp(4):{x,y};return{x:p.x,y:p.y,drop,bornAt:elapsed,color:drop?"#ffd45a":FOOD_COLORS[Math.floor(Math.random()*FOOD_COLORS.length)],value:drop?1.8:1,dead:false}}
function newPower(type=null,x=null,y=null){const p=x==null?rp(10):{x,y};return{x:p.x,y:p.y,type:type||POWERUP_TYPES[Math.floor(Math.random()*POWERUP_TYPES.length)],phase:Math.random()*6.28}}
function reserveDropSlots(need){let extra=Math.max(0,foods.length+need-1450);for(let i=0;i<foods.length&&extra>0;i++)if(!foods[i].drop&&!foods[i].dead){foods[i].dead=true;extra--;foodDirty=true}}
function dropPoints(pts){reserveDropSlots(Math.ceil(pts.length/2)+2);for(let i=0;i<pts.length;i+=2){const p=pts[i];if(inside(p,1))foods.push(newFood(true,p.x,p.y))}}
function dropBody(s){dropPoints(s.trail);if(!s.trail.length&&inside(s,1))foods.push(newFood(true,s.x,s.y))}
function cutHalf(s){if(!s.trail||s.trail.length<20)return;const cut=Math.max(12,Math.floor(s.trail.length*.5)),lost=s.trail.splice(cut);dropPoints(lost);s.lengthPts=Math.max(60,Math.floor(s.lengthPts*.5));s.bodyShotHits=0}
function gridKey(x,y){return(Math.floor(x/5))+","+(Math.floor(y/5))}
function buildFoodGrid(){foodGrid.clear();for(const f of foods){if(f.dead)continue;const k=gridKey(f.x,f.y);let a=foodGrid.get(k);if(!a)foodGrid.set(k,a=[]);a.push(f)}}
function nearbyFoods(a){const cx=Math.floor(a.x/5),cy=Math.floor(a.y/5),out=[];for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++){const q=foodGrid.get(x+","+y);if(q)out.push(...q)}return out}
function eatFood(a,isPlayer){let ate=0;for(const f of nearbyFoods(a)){if(f.dead)continue;if(d2(a,f)<.78*.78){f.dead=true;foodDirty=true;ate++;if(isPlayer){score+=f.drop?14:10;player.lengthPts=Math.min(650,player.lengthPts+(effects.growth>0?10:5)*(f.drop?1.2:1));if(ate===1)sfx("food")}else a.lengthPts=Math.min(680,a.lengthPts+4*f.value*(a.effects.growth>0?2:1))}}if(isPlayer&&ate)scoreEl.textContent=Math.round(score)}
function collectPower(a,isPlayer){for(let i=powerups.length-1;i>=0;i--){if(d2(a,powerups[i])>=1.25*1.25)continue;const t=powerups[i].type;powerups.splice(i,1);if(t==="cannon")a.cannonShots=3;else{const e=isPlayer?effects:a.effects;if(t==="shield")e.shield=Math.min(2,e.shield+1);else e[t]=Math.max(e[t],t==="speed"?6:8)}if(isPlayer){sfx("power");statusEl.textContent=t==="cannon"?"获得蛇身炮 · 3发":({magnet:"磁铁开启",speed:"疾速开启",shield:"获得护盾",growth:"双倍成长"}[t]||"获得道具")}}}
function updateEffects(e,dt){for(const k of["magnet","speed","growth"])e[k]=Math.max(0,e[k]-dt)}
function magnet(a,e,dt){if(e.magnet<=0)return;for(const o of foods){if(o.dead)continue;const dd=d2(a,o);if(dd>MAGNET_RADIUS*MAGNET_RADIUS||dd<.001)continue;const d=Math.sqrt(dd),q=(2+(MAGNET_RADIUS-d)*1.7)*dt;o.x+=(a.x-o.x)/d*q;o.y+=(a.y-o.y)/d*q}for(const o of powerups){const dd=d2(a,o);if(dd>MAGNET_RADIUS*MAGNET_RADIUS||dd<.001)continue;const d=Math.sqrt(dd),q=(2+(MAGNET_RADIUS-d)*1.7)*dt;o.x+=(a.x-o.x)/d*q;o.y+=(a.y-o.y)/d*q}}
function consumeShield(a,isPlayer,msg){const e=isPlayer?effects:a.effects;if(e.shield<=0)return false;e.shield--;a.spawnProtect=Math.max(a.spawnProtect,.9);if(isPlayer){sfx("shield");statusEl.textContent="护盾抵挡："+msg}return true}
function replenish(){let normal=0;for(const f of foods)if(!f.dead&&!f.drop)normal++;const target=Math.round(BASE_FOOD_TARGET+(currentDifficulty-1)*55);while(normal<target){foods.push(newFood());normal++}for(const f of foods)if(!f.dead&&f.drop&&elapsed-f.bornAt>34){f.dead=true;foodDirty=true}while(powerups.length<POWERUP_TARGET)powerups.push(newPower())}
function speak(t){if(!sfxOn||!("speechSynthesis" in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=1.08;u.pitch=.78;u.volume=1;speechSynthesis.speak(u)}catch(e){}}
function banner(text,cls=""){killBanner.textContent=text;killBanner.className="kill-banner show "+cls;killFlash.classList.remove("show");stage.classList.remove("shake");void killFlash.offsetWidth;killFlash.classList.add("show");stage.classList.add("shake");setTimeout(()=>{killBanner.classList.remove("show");stage.classList.remove("shake")},900)}
function recordKill(){kills++;killStreak++;comboCount=elapsed-lastKillAt<=8?comboCount+1:1;lastKillAt=elapsed;comboTimer=8;const m={2:["DOUBLE KILL · 双杀","Double Kill","c2"],3:["TRIPLE KILL · 三杀","Triple Kill","c3"],4:["QUADRA KILL · 四杀","Quadra Kill","c4"],5:["PENTA KILL · 五杀","Penta Kill","c5"]};if(m[comboCount]){banner(m[comboCount][0],m[comboCount][2]);sfx(comboCount>=4?"milestone":"kill");speak(m[comboCount][1])}else sfx("kill");if(killStreak===10){banner("LEGENDARY · 十连斩","legend");sfx("milestone");speak("Legendary")}if(killStreak===15){banner("UNSTOPPABLE · 十五连斩","legend");sfx("milestone");speak("Unstoppable")}score+=25}
function killAI(a,msg,credit=false){if(!a.alive)return;dropBody(a);a.alive=false;a.respawn=3+Math.random()*2.2;a.trail=[];a.cannonShots=0;a.bodyShotHits=0;if(credit)recordKill();statusEl.textContent=msg}
function diePlayer(msg){if(ended)return;dropBody(player);ended=true;playerRespawn=PLAYER_RESPAWN;boosting=false;boostBtn.classList.remove("active");effects={magnet:0,speed:0,growth:0,shield:0};player.cannonShots=0;player.bodyShotHits=0;killStreak=0;comboCount=0;sfx("death");statusEl.textContent=msg+" · 2.3秒后复活"}
function respawnPlayer(){const p=safeSpawn(true);Object.assign(player,{x:p.x,y:p.y,angle:Math.random()*6.28,lengthPts:110,spawnProtect:SPAWN_PROTECT,cannonShots:0,bodyShotHits:0});targetAngle=player.angle;seedTrail(player,72);ended=false;playerRespawn=0;cam={x:player.x,y:player.y};statusEl.textContent="已复活 · 全身保护"}
function danger(a,ang,look=2.8){const p={x:a.x+Math.cos(ang)*look,y:a.y+Math.sin(ang)*look};if(!inside(p,1.8))return true;if(!ended&&player.spawnProtect<=0&&hitTrail(p,player.trail,10,.72,4))return true;for(const o of ais)if(o!==a&&o.alive&&dist(a,o)<20&&hitTrail(p,o.trail,10,.7,4))return true;return false}
function forceEscape(a,sign=1){a.escapeTimer=1.8+Math.random()*.8;a.loopLock=4.5+Math.random()*2;a.escapeAngle=wrap(a.angle-(sign||1)*(1.05+Math.random()*.55));for(let k=0;k<4&&danger(a,a.escapeAngle,3.2);k++)a.escapeAngle=wrap(a.escapeAngle+(Math.random()<.5?-1:1)*.55);a.target=null;a.loopSamples=[]}
function monitorLoop(a,dt){a.loopLock=Math.max(0,a.loopLock-dt);a.progressTimer+=dt;a.sampleTimer-=dt;if(a.progressTimer>=2.2){const moved=Math.hypot(a.x-a.lastX,a.y-a.lastY);if(moved<3.4&&a.loopLock<=0)forceEscape(a,Math.random()<.5?-1:1);a.lastX=a.x;a.lastY=a.y;a.progressTimer=0}if(a.sampleTimer>0)return;a.sampleTimer=.22;a.loopSamples.push({x:a.x,y:a.y,angle:a.angle});if(a.loopSamples.length>16)a.loopSamples.shift();if(a.loopSamples.length<11||a.loopLock>0)return;let signed=0,abs=0;for(let i=1;i<a.loopSamples.length;i++){const da=wrap(a.loopSamples[i].angle-a.loopSamples[i-1].angle);signed+=da;abs+=Math.abs(da)}const f=a.loopSamples[0],net=Math.hypot(a.x-f.x,a.y-f.y);if((Math.abs(signed)>Math.PI*1.7&&net<8)||(abs>Math.PI*2.35&&net<7))forceEscape(a,Math.sign(signed)||1)}
function selectVictim(a){if(!ended&&player.spawnProtect<=0){const dp=dist(a,player),chance=.34+currentDifficulty*.12+(a.elite?.18:0);if(dp<64&&(a.aggr>.5||Math.random()<chance))return player}let best=null,bd=1e9;for(const o of ais)if(o!==a&&o.alive&&o.spawnProtect<=0&&o.lengthPts<a.lengthPts*1.2){const d=dist(a,o);if(d<bd&&d<30){best=o;bd=d}}return best}
function nearestFoodFast(a){let b=null,bd=1e9,step=7,start=a.foodSeed%step;for(let i=start;i<foods.length;i+=step){const f=foods[i];if(f.dead)continue;const dd=d2(a,f)*(f.drop?.45:1);if(dd<bd){bd=dd;b=f}}return b}
function chooseAI(a,time){if(a.escapeTimer>0)return a.escapeAngle;let aim=a.angle,t=a.target;if(t){if(t.id){const d=dist(a,t),tv=t===player?BASE_SPEED*pSpeed():AI_BASE_SPEED*aiSpeed(t),baseLead=a.tactic==="hunter"?.75:a.tactic==="interceptor"?1.15:1.35,lead=clamp(baseLead+d*.012,.55,1.55),px=t.x+Math.cos(t.angle)*tv*lead,py=t.y+Math.sin(t.angle)*tv*lead,side=Math.sign(Math.sin(t.angle)*(a.x-t.x)-Math.cos(t.angle)*(a.y-t.y))||1,off=a.tactic==="hunter"?2.2:a.tactic==="interceptor"?clamp(d*.21,3,7):clamp(d*.27,4,8);if(d<8.5){a.attackMode="cut";aim=t.angle+side*Math.PI*.50}else if(d<30){a.attackMode="intercept";aim=Math.atan2(py+Math.cos(t.angle)*off*side-a.y,px-Math.sin(t.angle)*off*side-a.x)}else{a.attackMode="hunt";aim=Math.atan2(py-a.y,px-a.x)}if(a.sprintCooldown<=0&&d<30&&a.attackMode!=="hunt"){a.sprintTimer=1+Math.random()*.7;a.sprintCooldown=2.4+Math.random()*2.8}}else{a.attackMode="feed";aim=Math.atan2(t.y-a.y,t.x-a.x)}}aim+=Math.sin(time*.0012+a.wobble)*.022;if(!danger(a,aim,2.8))return aim;for(const z of[a.angle,a.angle-.24,a.angle+.24,a.angle-.5,a.angle+.5,a.angle-.86,a.angle+.86])if(!danger(a,z,3))return z;if(a.loopLock<=0)forceEscape(a,Math.random()<.5?-1:1);return a.escapeTimer>0?a.escapeAngle:a.angle}
function tryAIFire(a){if(a.cannonShots<=0||a.fireCooldown>0||!a.target||!a.target.id||a.target===a)return;const t=a.target;if(t===player&&ended)return;const d=dist(a,t);if(d>34)return;const tv=t===player?BASE_SPEED*pSpeed():AI_BASE_SPEED*aiSpeed(t),lead=clamp(d/BULLET_SPEED,.2,.95),px=t.x+Math.cos(t.angle)*tv*lead,py=t.y+Math.sin(t.angle)*tv*lead,aim=Math.atan2(py-a.y,px-a.x),err=Math.abs(wrap(aim-a.angle));if(err<.14){fireBullet(a,false);a.fireCooldown=1.15+Math.random()*1.2}}
function thinkAI(a,time){a.targetCooldown-=a.thinkTimer<=0?0:0;if(!a.target||a.targetCooldown<=0||(!a.target.alive&&a.target.id)){a.targetCooldown=clamp(.58/currentDifficulty*(.8+Math.random()*.35),.16,.58);a.target=selectVictim(a)||nearestFoodFast(a)}a.desiredAngle=chooseAI(a,time);tryAIFire(a);a.thinkTimer=clamp(.22/currentDifficulty*(.75+Math.random()*.5),.11,.24)}
function fireBullet(s,isPlayer){if(!s||s.cannonShots<=0||s.lengthPts<=62||gameStopped||(isPlayer&&ended))return false;s.cannonShots--;s.lengthPts=Math.max(60,s.lengthPts-9);const cap=Math.max(42,Math.round(s.lengthPts));if(s.trail.length>cap)s.trail.length=cap;const a=s.angle,ox=s.x+Math.cos(a)*1.15,oy=s.y+Math.sin(a)*1.15;bullets.push({x:ox,y:oy,px:ox,py:oy,vx:Math.cos(a)*BULLET_SPEED,vy:Math.sin(a)*BULLET_SPEED,life:3.2,owner:s,ownerPlayer:isPlayer,skin:s.skin});sfx("fire");if(isPlayer)statusEl.textContent="直线开炮 · 剩余 "+s.cannonShots+" 发";return true}
function bulletHeadHit(b,t){const rr=.82+.12*(bodyWidth(t)/20);return d2(b,t)<rr*rr}
function applyBodyShot(t,b){t.bodyShotHits=(t.bodyShotHits||0)+1;sfx("hit");if(t.bodyShotHits>=3){cutHalf(t);if(t===player)statusEl.textContent="身体累计中炮3次 · 尾部断裂一半";else if(b.ownerPlayer)statusEl.textContent="命中3次 · AI 身体断裂一半"}else if(t===player)statusEl.textContent="身体中炮 "+t.bodyShotHits+"/3";else if(b.ownerPlayer)statusEl.textContent="AI 身体中炮 "+t.bodyShotHits+"/3"}
function updateBullets(dt){for(const b of bullets){if(b.dead)continue;b.px=b.x;b.py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||!inside(b,.2)){b.dead=true;continue}const targets=[];if(!ended&&player!==b.owner&&player.spawnProtect<=0)targets.push(player);for(const a of ais)if(a.alive&&a!==b.owner&&a.spawnProtect<=0)targets.push(a);for(const t of targets){if(bulletHeadHit(b,t)){b.dead=true;if(t===player)diePlayer("被直线炮弹命中头部");else killAI(t,b.ownerPlayer?"炮弹爆头 AI":"AI 炮弹爆头",b.ownerPlayer);break}const hi=findTrailHit(b,t.trail,8,.58);if(hi>=0){b.dead=true;applyBodyShot(t,b);break}}}bullets=bullets.filter(b=>!b.dead)}
function updatePlayer(dt){player.spawnProtect=Math.max(0,player.spawnProtect-dt);updateEffects(effects,dt);player.angle=turn(player.angle,targetAngle,PLAYER_TURN*dt);const v=BASE_SPEED*pSpeed();player.x+=Math.cos(player.angle)*v*dt;player.y+=Math.sin(player.angle)*v*dt;magnet(player,effects,dt);addTrail(player);eatFood(player,true);collectPower(player,true);if(!inside(player,PLAYER_R)){if(consumeShield(player,true,"边界碰撞")){player.x=clamp(player.x,1.5,WORLD-1.5);player.y=clamp(player.y,1.5,WORLD-1.5);targetAngle=player.angle=wrap(player.angle+Math.PI*.85);return}diePlayer("撞到边界");return}if(player.spawnProtect>0)return;for(const a of ais){if(!a.alive||a.spawnProtect>0)continue;if(dist(player,a)<.68){const ps=effects.shield>0,as=a.effects.shield>0;if(ps&&!as){consumeShield(player,true,"正面碰撞");killAI(a,"护盾反杀 AI",true);return}if(as&&!ps){consumeShield(a,false,"正面碰撞");diePlayer("被 AI 正面截杀");return}killAI(a,"正面相撞",false);diePlayer("正面撞上 AI");return}if(hitTrail(player,a.trail,8,BODY_R+.08,3)){if(consumeShield(player,true,"撞到 AI 身体"))return;diePlayer(a.attackMode==="cut"?"被 AI 横切封路击杀":"撞到 AI 身体");return}}}
function updateAI(a,dt,time){if(!a.alive){a.respawn-=dt;return}a.spawnProtect=Math.max(0,a.spawnProtect-dt);updateEffects(a.effects,dt);a.sprintCooldown=Math.max(0,a.sprintCooldown-dt);a.sprintTimer=Math.max(0,a.sprintTimer-dt);a.fireCooldown=Math.max(0,a.fireCooldown-dt);a.escapeTimer=Math.max(0,a.escapeTimer-dt);a.targetCooldown-=dt;a.thinkTimer-=dt;monitorLoop(a,dt);if(a.thinkTimer<=0)thinkAI(a,time);const pen=clamp((a.lengthPts-100)/900,0,.2),rate=(2.65+currentDifficulty*.5+(a.elite?.5:0))*(1-pen);a.angle=turn(a.angle,a.desiredAngle,rate*dt);const v=AI_BASE_SPEED*aiSpeed(a)*(a.elite?1.07:1);a.x+=Math.cos(a.angle)*v*dt;a.y+=Math.sin(a.angle)*v*dt;magnet(a,a.effects,dt);addTrail(a);eatFood(a,false);collectPower(a,false);if(!inside(a,.75)){a.x=clamp(a.x,1.1,WORLD-1.1);a.y=clamp(a.y,1.1,WORLD-1.1);const cx=WORLD/2-a.x,cy=WORLD/2-a.y;a.angle=Math.atan2(cy,cx);a.desiredAngle=a.angle;a.escapeAngle=a.angle;a.escapeTimer=1;a.loopLock=Math.max(a.loopLock,2);return}a.collisionTimer-=dt;if(a.spawnProtect>0||a.collisionTimer>0)return;a.collisionTimer=.055;if(!ended&&player.spawnProtect<=0&&dist(a,player)<.68){const as=a.effects.shield>0,ps=effects.shield>0;if(as&&!ps){consumeShield(a,false,"正面");diePlayer("被 AI 护盾截杀");return}if(ps&&!as){consumeShield(player,true,"正面");killAI(a,"护盾反杀 AI",true);return}killAI(a,"正面相撞",false);diePlayer("被 AI 正面撞杀");return}if(!ended&&hitTrail(a,player.trail,8,.56,4)){killAI(a,"你截杀了一条 AI",true);return}for(const o of ais)if(o!==a&&o.alive&&o.spawnProtect<=0&&dist(a,o)<18&&hitTrail(a,o.trail,8,.56,4)){killAI(a,"AI 被另一条蛇截杀");return}}
function scr(p){return{x:(p.x-cam.x)*SCALE+CW/2,y:(p.y-cam.y)*SCALE+CH/2}}function visible(p,pad=45){const q=scr(p);return q.x>-pad&&q.y>-pad&&q.x<CW+pad&&q.y<CH+pad}function snakeVisible(s,pad=170){if(visible(s,pad))return true;for(let i=0;i<s.trail.length;i+=8)if(visible(s.trail[i],pad))return true;return false}
function polyline(s,step=2){if(!s.trail.length)return;let p=scr(s.trail[0]);ctx.beginPath();ctx.moveTo(p.x,p.y);for(let i=step;i<s.trail.length;i+=step){const q=scr(s.trail[i]);ctx.lineTo(q.x,q.y)}}
const WORLD_GRAD=ctx.createLinearGradient(0,0,CW,CH);WORLD_GRAD.addColorStop(0,"#101b25");WORLD_GRAD.addColorStop(1,"#0a1118");
function drawWorld(){ctx.fillStyle="#771e27";ctx.fillRect(0,0,CW,CH);const tl=scr({x:0,y:0}),br=scr({x:WORLD,y:WORLD});ctx.fillStyle=WORLD_GRAD;ctx.fillRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.strokeStyle="#ff5865";ctx.lineWidth=5;ctx.strokeRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y)}
function drawCannon(s,sk,h,w){if(s.cannonShots<=0)return;ctx.save();ctx.translate(h.x,h.y);ctx.rotate(s.angle);ctx.strokeStyle="#0b1117";ctx.lineWidth=Math.max(7,w*.36);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-3,0);ctx.lineTo(18,0);ctx.stroke();ctx.strokeStyle=sk.accent;ctx.lineWidth=Math.max(4,w*.20);ctx.beginPath();ctx.moveTo(-2,0);ctx.lineTo(19,0);ctx.stroke();ctx.fillStyle=sk.accent;ctx.beginPath();ctx.arc(20,0,3.2,0,6.28);ctx.fill();ctx.restore()}
function drawSnake(s,isPlayer=false){if(!s.trail.length||!snakeVisible(s))return;const sk=SKINS[s.skin]||SKINS.qinglong,w=bodyWidth(s),h=scr(s);ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="rgba(0,0,0,.72)";ctx.lineWidth=w+6;polyline(s,2);ctx.stroke();ctx.strokeStyle=sk.body;ctx.lineWidth=w+2;polyline(s,2);ctx.stroke();ctx.strokeStyle=sk.head;ctx.lineWidth=w;polyline(s,2);ctx.stroke();ctx.fillStyle=sk.head;ctx.beginPath();ctx.arc(h.x,h.y,w*.64,0,6.28);ctx.fill();drawCannon(s,sk,h,w);if(!isPlayer&&s.elite){ctx.strokeStyle="#ffd96a";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,w*.86,0,6.28);ctx.stroke()}if((isPlayer?effects.shield:s.effects.shield)>0){ctx.strokeStyle="rgba(102,214,255,.85)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,w*.95+5,0,6.28);ctx.stroke()}if(s.spawnProtect>0){ctx.strokeStyle="rgba(220,240,255,.72)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,Math.max(38,w*2.9),0,6.28);ctx.stroke()}ctx.restore()}
function draw(){drawWorld();const tl=scr({x:0,y:0}),br=scr({x:WORLD,y:WORLD});ctx.save();ctx.beginPath();ctx.rect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.clip();for(const f of foods){if(f.dead||!visible(f,20))continue;const p=scr(f);if(f.drop){ctx.fillStyle="rgba(255,212,90,.22)";ctx.beginPath();ctx.arc(p.x,p.y,9,0,6.28);ctx.fill()}ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(p.x,p.y,f.drop?6:4,0,6.28);ctx.fill()}for(const p of powerups)if(visible(p,30)){const q=scr(p);ctx.fillStyle="#13283a";ctx.strokeStyle=p.type==="cannon"?"#ffd85a":"#9ee3ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,14,0,6.28);ctx.fill();ctx.stroke();ctx.font="15px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(p.type==="magnet"?"🧲":p.type==="speed"?"⚡":p.type==="shield"?"🛡️":p.type==="cannon"?"💥":"⭐",q.x,q.y)}for(const a of ais)if(a.alive)drawSnake(a,false);if(!ended)drawSnake(player,true);for(const b of bullets)if(visible(b,20)){const p=scr(b),sk=SKINS[b.skin]||SKINS.qinglong;ctx.fillStyle=sk.accent;ctx.beginPath();ctx.arc(p.x,p.y,5.2,0,6.28);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.75)";ctx.lineWidth=1.5;ctx.stroke()}ctx.restore()}
function ui(){aliveEl.textContent=ais.filter(a=>a.alive).length;targetAIEl.textContent=currentTargetAI;difficultyEl.textContent=currentDifficulty.toFixed(2);clockEl.textContent=fmt(elapsed);pressureEl.textContent=`竞技场压力 ${Math.round(currentPressure*100)}%`;streakEl.textContent=`连斩 ${killStreak}`;scoreEl.textContent=Math.round(score);killsEl.textContent=kills;speedEl.textContent=`速度 ${Math.round(pSpeed()*100)}%`;for(const k of["magnet","speed","shield","growth"]){fxEls[k].classList.toggle("on",effects[k]>0);fxEls[k].textContent={magnet:"🧲 磁铁",speed:"⚡ 疾速",shield:"🛡️ 护盾",growth:"⭐ 双倍成长"}[k]+(effects[k]>0?" "+(k==="shield"?"×"+effects[k]:effects[k].toFixed(1)+"s"):"")}fxEls.cannon.classList.toggle("on",player.cannonShots>0);fxEls.cannon.textContent="💥 蛇身炮"+(player.cannonShots>0?" ×"+player.cannonShots:"");fireBtn.classList.toggle("hidden",player.cannonShots<=0||ended);fireCount.textContent="×"+player.cannonShots;const rows=[];if(!ended)rows.push({n:"你",l:player.lengthPts});for(const a of ais)if(a.alive)rows.push({n:(a.elite?"★ ":"")+SKINS[a.skin].name+" AI",l:a.lengthPts});rows.sort((a,b)=>b.l-a.l);leaderEl.innerHTML="<b>排行榜</b>　"+rows.slice(0,5).map((r,i)=>`${i+1}. ${r.n} ${Math.round(r.l)}`).join("　")}
function step(dt,time){if(gameStopped)return;elapsed+=dt;spawnTicker-=dt;uiTicker-=dt;replenishTicker-=dt;comboTimer=Math.max(0,comboTimer-dt);if(!comboTimer)comboCount=0;buildFoodGrid();if(ended){playerRespawn-=dt;if(playerRespawn<=0)respawnPlayer()}else updatePlayer(dt);for(const a of ais)updateAI(a,dt,time);updateBullets(dt);if(spawnTicker<=0){spawnTicker=.7;ensureAI()}if(replenishTicker<=0){replenishTicker=.24;replenish()}if(foodDirty){foods=foods.filter(f=>!f.dead);foodDirty=false}const f=1-Math.exp(-7*dt);cam.x+=(player.x-cam.x)*f;cam.y+=(player.y-cam.y)*f;if(uiTicker<=0){uiTicker=.25;ui()}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;step(dt,now);draw();raf=requestAnimationFrame(loop)}
function setBoost(v){boosting=!!v&&!ended&&!gameStopped;boostBtn.classList.toggle("active",boosting);if(boosting)sfx("boost")}
function moveJoy(e){const b=joy.getBoundingClientRect(),dx=e.clientX-(b.left+b.width/2),dy=e.clientY-(b.top+b.height/2),l=Math.hypot(dx,dy)||1,max=b.width*.29,k=Math.min(1,max/l);stick.style.transform=`translate(${dx*k}px,${dy*k}px)`;if(l>4)targetAngle=Math.atan2(dy,dx)}function clearJoy(){joyPointer=null;stick.style.transform="translate(0,0)"}
joy.addEventListener("pointerdown",async e=>{await unlockAudio();joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)});joy.addEventListener("pointermove",e=>{if(e.pointerId===joyPointer)moveJoy(e)});joy.addEventListener("pointerup",e=>{if(e.pointerId===joyPointer)clearJoy()});joy.addEventListener("pointercancel",clearJoy);boostBtn.addEventListener("pointerdown",async e=>{await unlockAudio();boostBtn.setPointerCapture(e.pointerId);setBoost(true)});boostBtn.addEventListener("pointerup",()=>setBoost(false));boostBtn.addEventListener("pointercancel",()=>setBoost(false));fireBtn.addEventListener("pointerdown",async e=>{e.preventDefault();await unlockAudio();fireBullet(player,true);ui()});
function setSkin(n){if(!SKINS[n])return;currentSkin=n;if(player)player.skin=n;skinNameEl.textContent=SKINS[n].name;skinBtns.forEach(b=>b.classList.toggle("active",b.dataset.skin===n))}
function reset(){cancelAnimationFrame(raf);elapsed=0;score=0;kills=0;killStreak=0;comboCount=0;lastKillAt=-999;effects={magnet:0,speed:0,growth:0,shield:0};foods=[];powerups=[];bullets=[];ais=[];player=makePlayer();cam={x:90,y:90};targetAngle=player.angle;ended=false;for(let i=0;i<14;i++)ais.push(makeAI());for(let i=0;i<BASE_FOOD_TARGET;i++)foods.push(newFood());for(let i=0;i<POWERUP_TARGET;i++)powerups.push(newPower());gameStopped=!userStarted;last=performance.now();difficulty();ui();raf=requestAnimationFrame(loop)}
async function start(){await unlockAudio();userStarted=true;gameStopped=false;soundGate.classList.add("hidden");statusEl.textContent="竞技中";stopBtn.textContent="暂停";last=performance.now();tone(660,.09,.07,"triangle");tone(920,.12,.055,"triangle",.07)}
startGameBtn.addEventListener("click",start);$("restart").onclick=async()=>{await unlockAudio();userStarted=true;soundGate.classList.add("hidden");reset()};stopBtn.onclick=async()=>{await unlockAudio();if(!userStarted){await start();return}gameStopped=!gameStopped;stopBtn.textContent=gameStopped?"继续":"暂停";statusEl.textContent=gameStopped?"已暂停":"竞技中";if(!gameStopped)last=performance.now()};musicBtn.onclick=async()=>{await unlockAudio();musicOn=!musicOn;musicBtn.classList.toggle("off",!musicOn);musicOn?startMusic():stopMusic()};sfxBtn.onclick=async()=>{await unlockAudio();sfxOn=!sfxOn;sfxBtn.classList.toggle("off",!sfxOn);sfxBtn.textContent=sfxOn?"🔊":"🔇"};skinBtns.forEach(b=>b.onclick=()=>setSkin(b.dataset.skin));document.addEventListener("visibilitychange",()=>{if(document.hidden)setBoost(false)});
window.__snakeTest={snapshot:()=>({version:"V4.3.1",elapsed,difficulty:currentDifficulty,targetAI:currentTargetAI,aliveAI:ais.filter(a=>a.alive).length,foodCount:foods.length,kills,killStreak,playerCanTightCircle:true,aiLowFrequencyThink:true,aiTactics:["hunter","interceptor","ambusher"],cannonStraight:true,cannonShots:player.cannonShots,bodyHitsToCut:3,headshotKills:true}),giveCannon:()=>{player.cannonShots=3;ui();return player.cannonShots},fire:()=>fireBullet(player,true),forceAIHunt:(i=0)=>{const a=ais[i];a.aggr=1;a.target=player;a.targetCooldown=1;a.thinkTimer=0;thinkAI(a,performance.now());return{tactic:a.tactic,mode:a.attackMode,desired:a.desiredAngle}},forceBodyHit:(i=0)=>{const a=ais[i];applyBodyShot(a,{ownerPlayer:true});return{hits:a.bodyShotHits,length:a.lengthPts}},forceHeadshot:(i=0)=>{const a=ais[i];killAI(a,"测试爆头",true);return{alive:a.alive,kills}}};
setSkin("qinglong");reset();
})();