(()=>{"use strict";
const $=id=>document.getElementById(id),cv=$("board"),ctx=cv.getContext("2d",{alpha:false}),CW=cv.width,CH=cv.height;
const scoreEl=$("score"),aliveEl=$("alive"),killsEl=$("kills"),statusEl=$("status"),clockEl=$("clock"),difficultyEl=$("difficulty"),targetAIEl=$("targetAI"),pressureEl=$("pressureLabel"),streakEl=$("streakLabel"),joy=$("joy"),stick=$("stick"),boostBtn=$("boost"),fireBtn=$("fire"),fireCount=$("fireCount"),bladeBtn=$("blade"),bladeCount=$("bladeCount"),speedEl=$("speed"),skinNameEl=$("skinName"),leaderEl=$("leader"),musicBtn=$("musicBtn"),sfxBtn=$("sfxBtn"),soundGate=$("soundGate"),startGameBtn=$("startGame"),stopBtn=$("stop"),stage=document.querySelector(".stage");
const fxEls={magnet:$("fxMagnet"),speed:$("fxSpeed"),shield:$("fxShield"),growth:$("fxGrowth"),cannon:$("fxCannon"),blade:$("fxBlade")},skinBtns=[...document.querySelectorAll(".skin")];
const WORLD=180,SCALE=18.5,BASE_SPEED=6.15,BOOST=1.48,PLAYER_TURN=5.45,AI_SPEED=6.12,TRAIL_GAP=.19,FOOD_TARGET=265,POWER_TARGET=10,BULLET_SPEED=18,BLADE_SPEED=28,SPAWN_PROTECT=2.0;
const FOOD_COLORS=["#55e3ff","#ffd85a","#ff6c93","#b27cff","#67e08a","#ff9d50","#6f9cff"];
const SKINS={qinglong:{name:"青龙·鳞甲",body:"#17875f",head:"#54e6ab",accent:"#efd267",pattern:"scale"},neon:{name:"霓虹·电弧",body:"#314ae0",head:"#61f2ff",accent:"#e85dff",pattern:"neon"},lava:{name:"熔岩·裂纹",body:"#8c3026",head:"#ff6b2c",accent:"#ffd166",pattern:"lava"},ice:{name:"冰晶·棱甲",body:"#64c8ef",head:"#d5f8ff",accent:"#ffffff",pattern:"ice"},star:{name:"星空·星尘",body:"#403795",head:"#9488ff",accent:"#f4edff",pattern:"star"},candy:{name:"糖果·条纹",body:"#ef5fa5",head:"#ffc0de",accent:"#7ef1ea",pattern:"candy"},mech:{name:"机甲·装甲",body:"#657688",head:"#cbd6df",accent:"#f2c14f",pattern:"mech"},bee:{name:"蜂皇·环纹",body:"#e6ad1d",head:"#ffdc68",accent:"#1d2229",pattern:"bee"},shadow:{name:"暗夜·赤瞳",body:"#202532",head:"#40495f",accent:"#ff405e",pattern:"shadow"},jade:{name:"翡翠·云纹",body:"#1f9b83",head:"#8cf1d3",accent:"#f4d98a",pattern:"jade"}};
let player,ais=[],foods=[],powerups=[],bullets=[],blades=[],vanish=[],foodGrid=new Map(),cam={x:90,y:90},targetAngle=0,last=performance.now(),raf=0,joyPointer=null,boosting=false,ended=false,respawnTimer=0,currentSkin="qinglong",effects={magnet:0,speed:0,growth:0,shield:0},elapsed=0,score=0,kills=0,killStreak=0,gameStopped=true,userStarted=false,currentDifficulty=1,currentTargetAI=15,currentPressure=0,uiTick=0,replenishTick=0,aiGiftTick=2.5,sfxOn=true,musicOn=true,audioCtx=null,musicTimer=null,wind={active:false,timer:20+Math.random()*15,duration:0,angle:0,force:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),d2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y},dist=(a,b)=>Math.sqrt(d2(a,b));
function wrap(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}function turn(a,b,m){return a+clamp(wrap(b-a),-m,m)}function inside(p,m=.6){return p.x>=m&&p.y>=m&&p.x<=WORLD-m&&p.y<=WORLD-m}function rp(m=5){return{x:m+Math.random()*(WORLD-2*m),y:m+Math.random()*(WORLD-2*m)}}function fmt(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(Math.floor(s%60)).padStart(2,"0")}
function tone(f=440,d=.06,g=.08,type="sine"){if(!audioCtx||!sfxOn||audioCtx.state!=="running")return;const t=audioCtx.currentTime,o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(audioCtx.destination);o.start(t);o.stop(t+d+.02)}function sfx(k){if(k==="food"){tone(760,.035,.05);tone(1100,.03,.025)}else if(k==="power"){tone(520,.08,.12,"triangle");tone(900,.1,.08)}else if(k==="fire"){tone(120,.06,.2,"square");tone(430,.08,.11,"sawtooth")}else if(k==="blade"){tone(980,.08,.12,"sawtooth");tone(620,.12,.08,"triangle")}else if(k==="hit"){tone(210,.07,.14,"square")}else if(k==="death"){tone(150,.24,.18,"sawtooth");tone(75,.3,.12,"triangle")}else if(k==="kill"){tone(150,.1,.16,"square");tone(650,.13,.11,"triangle")}else if(k==="wind"){tone(260,.18,.05,"triangle")}}
async function unlockAudio(){if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}}if(audioCtx&&audioCtx.state==="suspended")try{await audioCtx.resume()}catch(e){}if(musicOn&&audioCtx&&!musicTimer)startMusic()}
function startMusic(){if(!audioCtx||musicTimer||audioCtx.state!=="running")return;const notes=[220,277,330,277,247,330,370,330];let i=0;musicTimer=setInterval(()=>{if(!musicOn)return;const n=notes[i++%notes.length];tone(n,.16,.026,"triangle")},230)}function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function seedTrail(s,n){s.trail=[];for(let i=0;i<n;i++)s.trail.push({x:s.x-Math.cos(s.angle)*TRAIL_GAP*i,y:s.y-Math.sin(s.angle)*TRAIL_GAP*i})}function addTrail(s){if(!s.trail.length||d2(s,s.trail[0])>=TRAIL_GAP*TRAIL_GAP)s.trail.unshift({x:s.x,y:s.y});const cap=Math.min(560,Math.max(55,Math.round(s.lengthPts)));if(s.trail.length>cap)s.trail.length=cap}function hitTrail(p,t,skip=8,r=.55,step=4){const rr=r*r;for(let i=skip;i<t.length;i+=step)if(d2(p,t[i])<rr)return i;return-1}
function safeSpawn(forPlayer=false){for(let i=0;i<60;i++){const p=rp(12);if(ais.every(a=>!a.alive||dist(p,a)>(forPlayer?13:7))&&(!player||forPlayer||dist(p,player)>14))return p}return rp(15)}
function makePlayer(){const s={id:"player",x:90,y:90,angle:0,trail:[],lengthPts:115,spawnProtect:SPAWN_PROTECT,skin:currentSkin,cannonShots:0,bladeShots:0,bodyShotHits:0};seedTrail(s,78);return s}
function makeAI(){const p=safeSpawn(),elite=Math.random()<.24,len=95+Math.random()*(elite?300:190),styles=["hunter","cut","intercept","ambush"];const s={id:"ai_"+Math.random().toString(36).slice(2),x:p.x,y:p.y,angle:Math.random()*6.28,trail:[],lengthPts:len,alive:true,respawn:0,spawnProtect:SPAWN_PROTECT,skin:Object.keys(SKINS)[Math.floor(Math.random()*10)],effects:{magnet:0,speed:0,growth:0,shield:0},cannonShots:0,bladeShots:0,bodyShotHits:0,think:Math.random()*.18,desiredAngle:0,elite,style:styles[Math.floor(Math.random()*styles.length)],aggr:elite?.96:.72+Math.random()*.24,sprint:0,sprintCd:.5+Math.random()*1.4,fireCd:.5+Math.random(),bladeCd:1+Math.random()*1.4,escape:0,loop:[],loopTick:0,lastX:p.x,lastY:p.y,stuck:0,target:null};s.desiredAngle=s.angle;seedTrail(s,Math.min(330,Math.round(len*.7)));return s}
function difficulty(){const m=elapsed/60;currentDifficulty=clamp(1+m*.11,1,2.7);currentTargetAI=Math.round(clamp(15+m*.8,15,23));const live=ais.filter(a=>a.alive);currentPressure=clamp(live.length/currentTargetAI*.55+(live.reduce((q,a)=>q+a.lengthPts,0)/Math.max(1,live.length)/300)*.45,0,1)}function ensureAI(){difficulty();let live=ais.filter(a=>a.alive).length;while(live<currentTargetAI&&ais.length<23){ais.push(makeAI());live++}for(const a of ais)if(!a.alive&&a.respawn<=0&&live<currentTargetAI){Object.assign(a,makeAI());live++}}
function newFood(drop=false,x=null,y=null,vx=0,vy=0){const p=x==null?rp(5):{x,y};return{x:p.x,y:p.y,vx,vy,drop,born:elapsed,color:drop?"#ffd45a":FOOD_COLORS[Math.floor(Math.random()*FOOD_COLORS.length)],dead:false,value:drop?1.6:1}}
function scatterDrop(points){const step=Math.max(2,Math.ceil(points.length/150));for(let i=0;i<points.length;i+=step){const p=points[i];if(!inside(p,1))continue;const a=Math.random()*6.28,sp=.5+Math.random()*2.7;foods.push(newFood(true,p.x,p.y,Math.cos(a)*sp,Math.sin(a)*sp))}}
function dropBody(s){scatterDrop(s.trail)}
function vanishSegment(points){for(let i=0;i<points.length;i+=2){const p=points[i],a=Math.random()*6.28,sp=2+Math.random()*4;vanish.push({x:p.x,y:p.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.45+Math.random()*.35,max:.8})}if(vanish.length>360)vanish.splice(0,vanish.length-360)}
function cutHalfByCannon(s){if(s.trail.length<24)return;const cut=Math.max(14,Math.floor(s.trail.length*.5)),lost=s.trail.splice(cut);scatterDrop(lost);s.lengthPts=Math.max(62,Math.floor(s.lengthPts*.5));s.bodyShotHits=0}
function bladeCut(s,hitIndex){if(!s.trail||s.trail.length<20)return;const start=clamp(hitIndex+2,10,s.trail.length-2),lost=s.trail.splice(start);vanishSegment(lost);s.lengthPts=Math.max(60,Math.min(s.lengthPts,start));s.bodyShotHits=0}
function gridKey(x,y){return Math.floor(x/6)+","+Math.floor(y/6)}function buildFoodGrid(){foodGrid.clear();for(const f of foods){if(f.dead)continue;const k=gridKey(f.x,f.y);if(!foodGrid.has(k))foodGrid.set(k,[]);foodGrid.get(k).push(f)}}function nearFoods(a){const cx=Math.floor(a.x/6),cy=Math.floor(a.y/6),out=[];for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++){const q=foodGrid.get(x+","+y);if(q)out.push(...q)}return out}
function eatFood(s,isPlayer){for(const f of nearFoods(s)){if(f.dead||d2(s,f)>.8*.8)continue;f.dead=true;if(isPlayer){score+=f.drop?12:8;s.lengthPts=Math.min(600,s.lengthPts+(effects.growth>0?8:4)*(f.drop?1.2:1));sfx("food")}else s.lengthPts=Math.min(620,s.lengthPts+3.2*f.value)}}
function weightedPower(){const r=Math.random();return r<.27?"cannon":r<.52?"blade":r<.66?"shield":r<.78?"speed":r<.9?"magnet":"growth"}function newPower(type=null){const p=rp(9);return{x:p.x,y:p.y,type:type||weightedPower(),phase:Math.random()*6.28}}
function collectPower(s,isPlayer){for(let i=powerups.length-1;i>=0;i--){const p=powerups[i];if(d2(s,p)>1.25*1.25)continue;powerups.splice(i,1);if(p.type==="cannon")s.cannonShots=3;else if(p.type==="blade")s.bladeShots=1;else if(p.type==="shield")(isPlayer?effects:s.effects).shield=Math.min(2,(isPlayer?effects:s.effects).shield+1);else (isPlayer?effects:s.effects)[p.type]=p.type==="speed"?6:8;if(isPlayer){sfx("power");statusEl.textContent=p.type==="cannon"?"获得蛇身炮 · 3发":p.type==="blade"?"获得回旋飞镖 · 1发":"获得道具"}}}
function updateEffects(e,dt){for(const k of["magnet","speed","growth"])e[k]=Math.max(0,e[k]-dt)}function magnet(s,e,dt){if(e.magnet<=0)return;for(const f of foods){if(f.dead)continue;const dd=d2(s,f);if(dd>100||dd<.01)continue;const d=Math.sqrt(dd);f.x+=(s.x-f.x)/d*dt*5;f.y+=(s.y-f.y)/d*dt*5}}
function replenish(){let normal=0;for(const f of foods)if(!f.dead&&!f.drop)normal++;while(normal<FOOD_TARGET){const base=rp(5),count=Math.random()<.32?2+Math.floor(Math.random()*4):1;for(let k=0;k<count&&normal<FOOD_TARGET;k++){const a=Math.random()*6.28,r=Math.random()*4.5;foods.push(newFood(false,clamp(base.x+Math.cos(a)*r,2,WORLD-2),clamp(base.y+Math.sin(a)*r,2,WORLD-2)));normal++}}for(const f of foods)if(!f.dead&&f.drop&&elapsed-f.born>30)f.dead=true;while(powerups.length<POWER_TARGET)powerups.push(newPower());foods=foods.filter(f=>!f.dead);buildFoodGrid()}
function killAI(a,msg,credit=false){if(!a.alive)return;dropBody(a);a.alive=false;a.respawn=2.2+Math.random()*1.6;a.trail=[];a.cannonShots=a.bladeShots=0;if(credit){kills++;killStreak++;score+=30;sfx("kill")}statusEl.textContent=msg}
function diePlayer(msg){if(ended)return;dropBody(player);ended=true;respawnTimer=2.3;boosting=false;effects={magnet:0,speed:0,growth:0,shield:0};player.cannonShots=player.bladeShots=0;killStreak=0;sfx("death");statusEl.textContent=msg+" · 2.3秒后复活"}
function respawnPlayer(){const p=safeSpawn(true);Object.assign(player,{x:p.x,y:p.y,angle:Math.random()*6.28,lengthPts:115,spawnProtect:SPAWN_PROTECT,cannonShots:0,bladeShots:0,bodyShotHits:0});targetAngle=player.angle;seedTrail(player,78);cam={x:p.x,y:p.y};ended=false;statusEl.textContent="已复活 · 短暂无敌"}
function windPush(s,dt,mul=1){if(!wind.active)return;s.x+=Math.cos(wind.angle)*wind.force*dt*mul;s.y+=Math.sin(wind.angle)*wind.force*dt*mul}
function updateWind(dt){if(wind.active){wind.duration-=dt;if(wind.duration<=0){wind.active=false;wind.timer=26+Math.random()*24;statusEl.textContent="阵风结束"}}else{wind.timer-=dt;if(wind.timer<=0){wind.active=true;wind.duration=4.5+Math.random()*2.5;wind.angle=Math.random()*6.28;wind.force=.65+Math.random()*.55;const dirs=["东","东南","南","西南","西","西北","北","东北"],idx=(Math.round(wind.angle/(Math.PI/4))+8)%8;statusEl.textContent="突发阵风 · 向"+dirs[idx]+"吹";sfx("wind")}}}
function pSpeed(){return 1+(boosting?.48:0)+(effects.speed>0?.28:0)}function aiSpeed(a){return 1+(a.sprint>0?.5:0)+(a.effects.speed>0?.25:0)}
function selectTarget(a){if(!ended&&player.spawnProtect<=0&&dist(a,player)<90&&(a.aggr>.72||Math.random()<.85))return player;let best=null,bd=1e9;for(const o of ais)if(o!==a&&o.alive&&o.spawnProtect<=0){const d=dist(a,o);if(d<bd&&d<28){best=o;bd=d}}return best}
function danger(a,ang){const p={x:a.x+Math.cos(ang)*3,y:a.y+Math.sin(ang)*3};if(!inside(p,1.6))return true;if(!ended&&hitTrail(p,player.trail,10,.7,5)>=0)return true;for(const o of ais)if(o!==a&&o.alive&&dist(a,o)<20&&hitTrail(p,o.trail,10,.68,5)>=0)return true;return false}
function thinkAI(a){a.think=.12+Math.random()*.11;if(a.escape>0){a.desiredAngle=wrap(a.angle+1.15);return}a.target=selectTarget(a);let aim=a.angle;if(a.target){const t=a.target,d=dist(a,t),tv=t===player?BASE_SPEED*pSpeed():AI_SPEED*aiSpeed(t),lead=clamp(.55+d*.035,.65,1.75),px=t.x+Math.cos(t.angle)*tv*lead,py=t.y+Math.sin(t.angle)*tv*lead,side=Math.sign(Math.sin(t.angle)*(a.x-t.x)-Math.cos(t.angle)*(a.y-t.y))||1;if(d<7){aim=t.angle+side*Math.PI*.53}else if(a.style==="cut"||a.style==="intercept"||d<24){const off=clamp(d*.3,3.5,9);aim=Math.atan2(py+Math.cos(t.angle)*off*side-a.y,px-Math.sin(t.angle)*off*side-a.x)}else aim=Math.atan2(py-a.y,px-a.x);if(a.sprintCd<=0&&d<38){a.sprint=.9+Math.random()*.8;a.sprintCd=1.4+Math.random()*1.8}}else{let f=null,bd=1e9;for(let i=Math.floor(Math.random()*7);i<foods.length;i+=9){const q=foods[i];if(q.dead)continue;const dd=d2(a,q);if(dd<bd){bd=dd;f=q}}if(f)aim=Math.atan2(f.y-a.y,f.x-a.x)}if(danger(a,aim)){for(const z of[a.angle-.3,a.angle+.3,a.angle-.65,a.angle+.65,a.angle+1.05])if(!danger(a,z)){aim=z;break}}a.desiredAngle=aim}
function monitorLoop(a,dt){a.loopTick-=dt;a.stuck+=dt;if(a.stuck>2){const moved=Math.hypot(a.x-a.lastX,a.y-a.lastY);if(moved<3){a.escape=1.7;a.desiredAngle=wrap(a.angle+(Math.random()<.5?-1:1)*1.25)}a.lastX=a.x;a.lastY=a.y;a.stuck=0}if(a.loopTick>0)return;a.loopTick=.28;a.loop.push({x:a.x,y:a.y,a:a.angle});if(a.loop.length>12)a.loop.shift();if(a.loop.length<10)return;let spin=0;for(let i=1;i<a.loop.length;i++)spin+=Math.abs(wrap(a.loop[i].a-a.loop[i-1].a));const n=a.loop[0],move=Math.hypot(a.x-n.x,a.y-n.y);if(spin>Math.PI*2.2&&move<7){a.escape=1.9;a.desiredAngle=wrap(a.angle+(Math.random()<.5?-1:1)*1.35);a.loop=[]}}
function fireBullet(s,isPlayer){if(!s||s.cannonShots<=0||s.lengthPts<=65||gameStopped||(isPlayer&&ended))return;s.cannonShots--;s.lengthPts=Math.max(60,s.lengthPts-8);const a=s.angle;bullets.push({x:s.x+Math.cos(a)*1.2,y:s.y+Math.sin(a)*1.2,vx:Math.cos(a)*BULLET_SPEED,vy:Math.sin(a)*BULLET_SPEED,life:3.1,owner:s,ownerPlayer:isPlayer,skin:s.skin});sfx("fire");if(isPlayer)statusEl.textContent="直线开炮 · 剩余 "+s.cannonShots+" 发"}
function fireBlade(s,isPlayer){if(!s||s.bladeShots<=0||gameStopped||(isPlayer&&ended))return;s.bladeShots--;const a=s.angle;blades.push({x:s.x+Math.cos(a)*1.3,y:s.y+Math.sin(a)*1.3,vx:Math.cos(a)*BLADE_SPEED,vy:Math.sin(a)*BLADE_SPEED,life:WORLD/BLADE_SPEED*1.55,owner:s,ownerPlayer:isPlayer,angle:a,hit:new Set()});sfx("blade");if(isPlayer)statusEl.textContent="回旋飞镖发射 · 命中身体后直接断灭"}
function tryAIAttack(a){if(!a.target||a.target===a)return;const t=a.target;if(t===player&&ended)return;const d=dist(a,t),tv=t===player?BASE_SPEED*pSpeed():AI_SPEED*aiSpeed(t),lead=clamp(d/BULLET_SPEED,.2,1.1),px=t.x+Math.cos(t.angle)*tv*lead,py=t.y+Math.sin(t.angle)*tv*lead,aim=Math.atan2(py-a.y,px-a.x),err=Math.abs(wrap(aim-a.angle));if(a.cannonShots>0&&a.fireCd<=0&&d<46&&err<.21){fireBullet(a,false);a.fireCd=.7+Math.random()*.8}else if(a.bladeShots>0&&a.bladeCd<=0&&d<70&&err<.15){fireBlade(a,false);a.bladeCd=2}}
function updateBullets(dt){for(const b of bullets){if(b.dead)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||!inside(b,.1)){b.dead=true;continue}const targets=[];if(!ended&&b.owner!==player&&player.spawnProtect<=0)targets.push(player);for(const a of ais)if(a.alive&&a!==b.owner&&a.spawnProtect<=0)targets.push(a);for(const t of targets){if(d2(b,t)<.8*.8){b.dead=true;if(t===player)diePlayer("被炮弹击中头部");else killAI(t,b.ownerPlayer?"炮弹爆头 AI":"AI 炮弹爆头",b.ownerPlayer);break}const hi=hitTrail(b,t.trail,7,.58,3);if(hi>=0){b.dead=true;t.bodyShotHits=(t.bodyShotHits||0)+1;sfx("hit");if(t.bodyShotHits>=3){cutHalfByCannon(t);if(t===player)statusEl.textContent="身体累计中炮3次 · 后半身断落成食物";else if(b.ownerPlayer)statusEl.textContent="AI 中炮3次 · 后半身断落"}else if(t===player)statusEl.textContent="身体中炮 "+t.bodyShotHits+"/3";break}}}bullets=bullets.filter(b=>!b.dead)}
function updateBlades(dt){for(const b of blades){if(b.dead)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.angle+=dt*16;b.life-=dt;if(b.life<=0||!inside(b,.05)){b.dead=true;continue}const targets=[];if(!ended&&b.owner!==player&&player.spawnProtect<=0)targets.push(player);for(const a of ais)if(a.alive&&a!==b.owner&&a.spawnProtect<=0)targets.push(a);for(const t of targets){if(b.hit.has(t.id))continue;const hi=hitTrail(b,t.trail,5,.75,2);if(hi>=0){b.hit.add(t.id);bladeCut(t,hi);sfx("hit");if(t===player)statusEl.textContent="被飞镖击中 · 命中点之后身体已断灭";else if(b.ownerPlayer)statusEl.textContent="飞镖命中 AI · 后段身体直接消散"}}}blades=blades.filter(b=>!b.dead)}
function updateAI(a,dt){if(!a.alive){a.respawn-=dt;return}a.spawnProtect=Math.max(0,a.spawnProtect-dt);updateEffects(a.effects,dt);a.think-=dt;a.sprint=Math.max(0,a.sprint-dt);a.sprintCd=Math.max(0,a.sprintCd-dt);a.fireCd=Math.max(0,a.fireCd-dt);a.bladeCd=Math.max(0,a.bladeCd-dt);a.escape=Math.max(0,a.escape-dt);monitorLoop(a,dt);if(a.think<=0)thinkAI(a);tryAIAttack(a);const rate=(3.2+currentDifficulty*.65+(a.elite?.6:0))*(1-clamp((a.lengthPts-100)/1000,0,.18));a.angle=turn(a.angle,a.desiredAngle,rate*dt);const v=AI_SPEED*aiSpeed(a)*(a.elite?1.07:1);a.x+=Math.cos(a.angle)*v*dt;a.y+=Math.sin(a.angle)*v*dt;windPush(a,dt,.85);magnet(a,a.effects,dt);addTrail(a);eatFood(a,false);collectPower(a,false);if(!inside(a,.75)){a.x=clamp(a.x,1.2,WORLD-1.2);a.y=clamp(a.y,1.2,WORLD-1.2);a.desiredAngle=a.angle=Math.atan2(WORLD/2-a.y,WORLD/2-a.x);return}if(a.spawnProtect>0)return;if(!ended&&player.spawnProtect<=0){if(dist(a,player)<.68){if(effects.shield>0){effects.shield--;killAI(a,"护盾反杀 AI",true)}else diePlayer("被 AI 正面撞杀");return}if(hitTrail(a,player.trail,8,.56,4)>=0){killAI(a,"AI 撞上了你的身体",true);return}}for(const o of ais)if(o!==a&&o.alive&&o.spawnProtect<=0&&dist(a,o)<15&&hitTrail(a,o.trail,8,.56,5)>=0){killAI(a,"AI 被另一条蛇截杀");return}}
function updatePlayer(dt){player.spawnProtect=Math.max(0,player.spawnProtect-dt);updateEffects(effects,dt);player.angle=turn(player.angle,targetAngle,PLAYER_TURN*dt);const v=BASE_SPEED*pSpeed();player.x+=Math.cos(player.angle)*v*dt;player.y+=Math.sin(player.angle)*v*dt;windPush(player,dt,1);magnet(player,effects,dt);addTrail(player);eatFood(player,true);collectPower(player,true);if(!inside(player,.5)){if(effects.shield>0){effects.shield--;player.x=clamp(player.x,1.5,WORLD-1.5);player.y=clamp(player.y,1.5,WORLD-1.5);player.angle=targetAngle=wrap(player.angle+Math.PI*.9)}else diePlayer("撞到边界");return}if(player.spawnProtect>0)return;for(const a of ais){if(!a.alive||a.spawnProtect>0)continue;if(dist(player,a)<.68){if(a.effects.shield>0){a.effects.shield--;diePlayer("被 AI 护盾截杀")}else killAI(a,"正面相撞",false),diePlayer("正面撞上 AI");return}if(hitTrail(player,a.trail,8,.58,4)>=0){if(effects.shield>0){effects.shield--;statusEl.textContent="护盾抵挡了一次撞击"}else diePlayer("撞到 AI 身体");return}}}
function aiOffscreenGift(dt){aiGiftTick-=dt;if(aiGiftTick>0)return;aiGiftTick=1.9+Math.random()*2.4;const c=ais.filter(a=>a.alive&&dist(a,player)>45&&a.cannonShots<=0&&a.bladeShots<=0);if(!c.length)return;const a=c[Math.floor(Math.random()*c.length)];if(Math.random()<.72){if(Math.random()<.55)a.cannonShots=3;else a.bladeShots=1}}
function updateFoodMotion(dt){for(const f of foods){if(f.dead)continue;if(Math.abs(f.vx)+Math.abs(f.vy)>.02){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=Math.pow(.08,dt);f.vy*=Math.pow(.08,dt);f.x=clamp(f.x,1,WORLD-1);f.y=clamp(f.y,1,WORLD-1)}}}
function updateVanish(dt){for(const p of vanish){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.18,dt);p.vy*=Math.pow(.18,dt)}vanish=vanish.filter(p=>p.life>0)}
function scr(p){return{x:(p.x-cam.x)*SCALE+CW/2,y:(p.y-cam.y)*SCALE+CH/2}}function visible(p,pad=45){const q=scr(p);return q.x>-pad&&q.y>-pad&&q.x<CW+pad&&q.y<CH+pad}function snakeVisible(s){if(visible(s,150))return true;for(let i=0;i<s.trail.length;i+=12)if(visible(s.trail[i],100))return true;return false}
const grad=ctx.createLinearGradient(0,0,CW,CH);grad.addColorStop(0,"#101b25");grad.addColorStop(1,"#081018");
function drawWorld(){ctx.fillStyle="#711c25";ctx.fillRect(0,0,CW,CH);const tl=scr({x:0,y:0}),br=scr({x:WORLD,y:WORLD});ctx.fillStyle=grad;ctx.fillRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.strokeStyle="#ff5865";ctx.lineWidth=5;ctx.strokeRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);if(wind.active){ctx.save();ctx.globalAlpha=.16;ctx.strokeStyle="#bfe9ff";ctx.lineWidth=2;const dx=Math.cos(wind.angle)*55,dy=Math.sin(wind.angle)*55;for(let y=55;y<CH;y+=95)for(let x=40;x<CW;x+=120){ctx.beginPath();ctx.moveTo(x-dx*.3,y-dy*.3);ctx.lineTo(x+dx*.7,y+dy*.7);ctx.stroke()}ctx.restore()}}
function pathSnake(s,step=3){if(!s.trail.length)return;let p=scr(s.trail[0]);ctx.beginPath();ctx.moveTo(p.x,p.y);for(let i=step;i<s.trail.length;i+=step){p=scr(s.trail[i]);ctx.lineTo(p.x,p.y)}}
function bodyWidth(s){return Math.min(25,10+Math.max(0,s.lengthPts-70)*.035)}
function drawSnake(s,isPlayer=false){if(!s.trail.length||!snakeVisible(s))return;const sk=SKINS[s.skin]||SKINS.qinglong,w=bodyWidth(s),h=scr(s);ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="rgba(0,0,0,.7)";ctx.lineWidth=w+6;pathSnake(s,3);ctx.stroke();ctx.strokeStyle=sk.body;ctx.lineWidth=w+2;pathSnake(s,3);ctx.stroke();ctx.strokeStyle=sk.head;ctx.lineWidth=w;pathSnake(s,3);ctx.stroke();for(let i=8;i<Math.min(s.trail.length,190);i+=11){const p=scr(s.trail[i]);if(!visible(s.trail[i],20))continue;ctx.fillStyle=sk.accent;ctx.globalAlpha=.62;ctx.beginPath();ctx.arc(p.x,p.y,1.6,0,6.28);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle=sk.head;ctx.beginPath();ctx.arc(h.x,h.y,w*.63,0,6.28);ctx.fill();ctx.save();ctx.translate(h.x,h.y);ctx.rotate(s.angle);ctx.fillStyle=sk.accent;ctx.beginPath();ctx.arc(w*.2,-w*.23,2,0,6.28);ctx.arc(w*.2,w*.23,2,0,6.28);ctx.fill();if(s.cannonShots>0){ctx.strokeStyle=sk.accent;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(18,0);ctx.stroke()}ctx.restore();if((isPlayer?effects.shield:s.effects.shield)>0){ctx.strokeStyle="rgba(100,220,255,.9)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,w+5,0,6.28);ctx.stroke()}ctx.restore()}
function drawPower(p){const q=scr(p);ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle="#142737";ctx.strokeStyle=p.type==="cannon"?"#ffd85a":p.type==="blade"?"#ff79d6":"#9ee3ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,14,0,6.28);ctx.fill();ctx.stroke();if(p.type==="blade"){ctx.fillStyle="#fff0fb";ctx.strokeStyle="#ff79d6";for(let k=0;k<4;k++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(11,0);ctx.lineTo(4,4);ctx.closePath();ctx.fill();ctx.stroke()}}else{ctx.font="15px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#fff";ctx.fillText(p.type==="magnet"?"🧲":p.type==="speed"?"⚡":p.type==="shield"?"🛡️":p.type==="cannon"?"💥":"⭐",0,0)}ctx.restore()}
function draw(){drawWorld();const tl=scr({x:0,y:0}),br=scr({x:WORLD,y:WORLD});ctx.save();ctx.beginPath();ctx.rect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.clip();for(const f of foods){if(f.dead||!visible(f,20))continue;const p=scr(f);ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(p.x,p.y,f.drop?5.1:3.5,0,6.28);ctx.fill()}for(const p of powerups)if(visible(p,30))drawPower(p);for(const a of ais)if(a.alive)drawSnake(a,false);if(!ended)drawSnake(player,true);for(const b of bullets)if(visible(b,20)){const p=scr(b),sk=SKINS[b.skin]||SKINS.qinglong;ctx.fillStyle=sk.accent;ctx.beginPath();ctx.arc(p.x,p.y,5,0,6.28);ctx.fill()}for(const b of blades)if(visible(b,30)){const p=scr(b);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(b.angle);ctx.fillStyle="#fff0fb";ctx.strokeStyle="#ff79d6";ctx.lineWidth=2;for(let k=0;k<4;k++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(14,0);ctx.lineTo(5,5);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}for(const p of vanish)if(visible(p,20)){const q=scr(p);ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle="#f7b9ef";ctx.beginPath();ctx.arc(q.x,q.y,2.5,0,6.28);ctx.fill()}ctx.globalAlpha=1;ctx.restore()}
function ui(){aliveEl.textContent=ais.filter(a=>a.alive).length;targetAIEl.textContent=currentTargetAI;difficultyEl.textContent=currentDifficulty.toFixed(2);clockEl.textContent=fmt(elapsed);pressureEl.textContent="竞技场压力 "+Math.round(currentPressure*100)+"%";streakEl.textContent="连斩 "+killStreak;scoreEl.textContent=Math.round(score);killsEl.textContent=kills;speedEl.textContent="速度 "+Math.round(pSpeed()*100)+"%";for(const k of["magnet","speed","shield","growth"])fxEls[k].classList.toggle("on",effects[k]>0);fxEls.cannon.classList.toggle("on",player.cannonShots>0);fxEls.blade.classList.toggle("on",player.bladeShots>0);fireBtn.classList.toggle("hidden",player.cannonShots<=0);bladeBtn.classList.toggle("hidden",player.bladeShots<=0);fireCount.textContent="×"+player.cannonShots;bladeCount.textContent="×"+player.bladeShots;if(wind.active)pressureEl.textContent+=" · 🌬️ 阵风";const top=[...ais.filter(a=>a.alive).sort((a,b)=>b.lengthPts-a.lengthPts).slice(0,3)].map((a,i)=>(i+1)+". AI "+Math.round(a.lengthPts));leaderEl.textContent="排行榜："+top.join(" · ")}
function frame(t){const dt=Math.min(.04,(t-last)/1000||.016);last=t;if(!gameStopped&&userStarted){elapsed+=dt;updateWind(dt);updateFoodMotion(dt);updateVanish(dt);if(ended){respawnTimer-=dt;if(respawnTimer<=0)respawnPlayer()}else updatePlayer(dt);for(const a of ais)updateAI(a,dt);updateBullets(dt);updateBlades(dt);aiOffscreenGift(dt);ensureAI();replenishTick-=dt;if(replenishTick<=0){replenish();replenishTick=.45}cam.x+=(player.x-cam.x)*Math.min(1,dt*5);cam.y+=(player.y-cam.y)*Math.min(1,dt*5);uiTick-=dt;if(uiTick<=0){ui();uiTick=.16}}draw();raf=requestAnimationFrame(frame)}
function joyMove(e){if(joyPointer!==null&&e.pointerId!==joyPointer)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy)||1,max=r.width*.34,nx=dx/d*Math.min(d,max),ny=dy/d*Math.min(d,max);stick.style.transform=`translate(${nx}px,${ny}px)`;targetAngle=Math.atan2(dy,dx)}joy.addEventListener("pointerdown",e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)});joy.addEventListener("pointermove",joyMove);function joyUp(e){if(e.pointerId!==joyPointer)return;joyPointer=null;stick.style.transform="translate(0,0)"}joy.addEventListener("pointerup",joyUp);joy.addEventListener("pointercancel",joyUp);
function boostOn(e){e.preventDefault();boosting=true;boostBtn.classList.add("active")}function boostOff(){boosting=false;boostBtn.classList.remove("active")}boostBtn.addEventListener("pointerdown",boostOn);boostBtn.addEventListener("pointerup",boostOff);boostBtn.addEventListener("pointercancel",boostOff);fireBtn.addEventListener("pointerdown",e=>{e.preventDefault();fireBullet(player,true)});bladeBtn.addEventListener("pointerdown",e=>{e.preventDefault();fireBlade(player,true)});
startGameBtn.addEventListener("click",async()=>{await unlockAudio();userStarted=true;gameStopped=false;soundGate.style.display="none";statusEl.textContent="开始竞技"});stopBtn.addEventListener("click",()=>{gameStopped=!gameStopped;stopBtn.textContent=gameStopped?"继续":"暂停";statusEl.textContent=gameStopped?"已暂停":"继续竞技"});$("restart").addEventListener("click",()=>location.reload());musicBtn.addEventListener("click",()=>{musicOn=!musicOn;musicBtn.textContent=musicOn?"♫":"♩";if(musicOn)startMusic();else stopMusic()});sfxBtn.addEventListener("click",()=>{sfxOn=!sfxOn;sfxBtn.textContent=sfxOn?"🔊":"🔇"});
skinBtns.forEach(b=>b.addEventListener("click",()=>{skinBtns.forEach(x=>x.classList.remove("active"));b.classList.add("active");currentSkin=b.dataset.skin;player.skin=currentSkin;skinNameEl.textContent=SKINS[currentSkin].name}));
player=makePlayer();targetAngle=player.angle;for(let i=0;i<15;i++)ais.push(makeAI());for(let i=0;i<FOOD_TARGET;i++)foods.push(newFood());for(let i=0;i<POWER_TARGET;i++)powerups.push(newPower());buildFoodGrid();ui();last=performance.now();raf=requestAnimationFrame(frame);
})();